const paragraphData = [
  {
    styleName: "Lesson_A-hd",
    content: "Read Chapter 1 RI.6.2, RST.6.2, SL.6.1\r",
    parentPageName: "3",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "1", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_B-hd",
    content: "Set a Purpose\r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "If necessary, use the Scaffolded Preview and Cognates for Essential Vocabulary to help students access the text.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "V", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Read aloud the supporting question on page 6: How does climate influence the development of biomes?\r",
    parentPageName: "3",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "w", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "f", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "v", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "p", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "f", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "b", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "?", style: "Italic" },
    ],
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content:
      "Say: As you read this chapter, you will use a strategy called Q-Notes to help you understand how climate influences the development of biomes.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: " ", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "i", style: "i" },
      { character: "l", style: "i" },
      { character: "l", style: "i" },
      { character: " ", style: "i" },
      { character: "u", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "g", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "l", style: "i" },
      { character: "e", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "Q", style: "i" },
      { character: "-", style: "i" },
      { character: "N", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "l", style: "i" },
      { character: "p", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: " ", style: "i" },
      { character: "u", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "f", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "v", style: "i" },
      { character: "e", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "p", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "b", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Display the Q-Notes sample shown in the right margin.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "D", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "Q", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "N", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content:
      "Say: The Q-Notes process is a form of note-taking. As you read, write down questions in the left column. You can do this by rewriting the headings, subheadings, and topic sentences as questions. Continue reading to find the answers, and record them in the right column of the Q-Notes chart. Q-Notes help you focus on the most important information in a text.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "Q", style: "i" },
      { character: "-", style: "i" },
      { character: "N", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "r", style: "i" },
      { character: "o", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "f", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "n", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "-", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "k", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "A", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: " ", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "r", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "q", style: "i" },
      { character: "u", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "e", style: "i" },
      { character: "f", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "o", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "m", style: "i" },
      { character: "n", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "Y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "b", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "w", style: "i" },
      { character: "r", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: "s", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "b", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: "s", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: "p", style: "i" },
      { character: "i", style: "i" },
      { character: "c", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "q", style: "i" },
      { character: "u", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "C", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "u", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "f", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "s", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "s", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "c", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "r", style: "i" },
      { character: "i", style: "i" },
      { character: "g", style: "i" },
      { character: "h", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "o", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "m", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "Q", style: "i" },
      { character: "-", style: "i" },
      { character: "N", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "Q", style: "i" },
      { character: "-", style: "i" },
      { character: "N", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "l", style: "i" },
      { character: "p", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: " ", style: "i" },
      { character: "f", style: "i" },
      { character: "o", style: "i" },
      { character: "c", style: "i" },
      { character: "u", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "m", style: "i" },
      { character: "o", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "p", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "f", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "x", style: "i" },
      { character: "t", style: "i" },
      { character: ".", style: "i" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Read aloud page 10 and model how you use the Q-Notes format.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "0", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "Q", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "N", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Have students create a Q-Notes chart on notebook paper, or distribute copies of BLM 1.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "Q", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "N", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "B", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "M", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Show students how you form a question from the topic sentence, How does latitude affect climate?  Write the question in the left column of the Q-Notes chart. Then have students read to find the answer. Have them record their answers in the right column, using a short answer, picture, or any form of note-taking that effectively helps them capture the information. Circulate to monitor and provide help as needed. Remind students that asking questions about what they read will help them focus on and summarize the key ideas in each chapter.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "o", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: "u", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "f", style: "i" },
      { character: "f", style: "i" },
      { character: "e", style: "i" },
      { character: "c", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "?", style: "i" },
      { character: " ", style: "i" },
      { character: " ", style: "[None]" },
      { character: "W", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "Q", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "N", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_B-hd",
    content: "Summarize Key Concepts: Think and Write Together\r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "K", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "W", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Invite students to share their Q-Notes. What questions did they ask in the left column? Do the answers they recorded in the right column provide information needed to understand central ideas/concepts? Provide time for students to share and discuss their chapter summaries with the class.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "Q", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "N", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "W", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "?", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "D", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "?", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Use the Sentence Frames to Support Collaborative Conversation for English learners.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "U", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "F", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "As a group, construct a two- to three-sentence written summary of the key ideas in the chapter. If students need more support to summarize the text, explicitly model strategies for summarizing.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
];
module.exports = paragraphData;
