const paragraphData = [
  {
    styleName: "B-hd",
    content: "Summarize Key Concepts: Think and Write Together\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "K", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "B-subhd" },
      { character: "h", style: "B-subhd" },
      { character: "i", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "k", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "a", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "W", style: "B-subhd" },
      { character: "r", style: "B-subhd" },
      { character: "i", style: "B-subhd" },
      { character: "t", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "T", style: "B-subhd" },
      { character: "o", style: "B-subhd" },
      { character: "g", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "t", style: "B-subhd" },
      { character: "h", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "r", style: "B-subhd" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Invite students to share their Double Entry Journals. What central ideas and key concepts did they list in the second column? Do the notes they recorded in the third column provide the details needed to understand these central ideas/concepts? Provide time for students to share and discuss their chapter summaries with the class.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "J", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: "?", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "/", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: "?", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "c", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Use the Sentence Frames to Support Collaborative Conversation for English learners. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "U", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "As a group, construct a two- to three-sentence written summary of the key ideas in the chapter. If students need more support to summarize the text, explicitly model strategies for summarizing.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "u", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: "-", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "-", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "g", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Model Summarizing \r",
    parentPageName: "4",
    characterStyles: [
      { character: "M", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: When we summarize, we include only the most important information in a text. We look for the central ideas. We don’t include all of the details. Let’s summarize a section of this chapter together. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "W", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "z", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "W", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "W", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "SINGLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "L", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "SINGLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "z", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Reread the “Aquatic Habitats” section on pages 10–12. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "A", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "H", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: "0", style: "" },
      { character: "EN_DASH", style: "" },
      { character: "1", style: "" },
      { character: "2", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: There is a lot of information in this section. I ask myself, “What is the central idea this writer wants me to understand about aquatic habitats?”\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "DOUBLE_LEFT_QUOTE", style: "teacher-talk" },
      { character: "W", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "q", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "?", style: "teacher-talk" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Allow responses. Support students to recognize that the author wants readers to understand what an aquatic habitat is and that they vary in type. He provides details about the specific aquatic habitats, including the organisms that live there, so that readers have a thorough understanding.   \r",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "g", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "y", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "H", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: " ", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: In my summary, I will include only the central idea. I will not include details about each type of aquatic habitat.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "I", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "q", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "[Basic Paragraph]",
    content: "\r",
    parentPageName: "4",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Label",
    content: "\nSample Summary (Chapter 1)\r",
    parentPageName: "4",
    characterStyles: [
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "S", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: ")", style: "" },
      { character: "", style: "" },
    ],
  },
  {
    styleName: "Sample-body-txt",
    content:
      "Aquatic environments differ from one another based on the amount of salinity, or salt in the water. Oceans, for example, have a great amount of salinity while rivers and lakes are freshwater bodies, so they have very little salinity.",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "y", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "w", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "y", style: "" },
      { character: ".", style: "" },
    ],
  },
];
module.exports = paragraphData;
