const paragraphData = [bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  {
    styleName: "[No Paragraph Style]",
    content: "",
    parentPageName: "3",
    characterStyles: [
      { character: "", style: "[None]" }
    ]
  },
  {
    styleName: "Chart-hd",
    content: "Support for English Learners",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" }
    ]
  },
  {
    styleName: "Chart-subhd",
    content: "Scaffolded Preview\r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Chapter 1\r",
    parentPageName: "3",
    characterStyles: [
      { character: "C", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "p", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "1", style: "b" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Page 7. What does it mean to be alive? (Allow responses.) We will find out how scientists define life.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "7", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "Chart-italic" },
      { character: "W", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" },
      { character: " ", style: "Chart-italic" },
      { character: "(", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: ")", style: "[None]" },
      { character: " ", style: "Chart-italic" },
      { character: "W", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Page 8. Look at the photos. What do the photos show?\r",
    parentPageName: "3",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "8", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "Chart-italic" },
      { character: "L", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "W", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Pages 10–11. What do these diagrams show? \r",
    parentPageName: "3",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "1", style: "b" },
      { character: "0", style: "b" },
      { character: "EN_DASH", style: "b" },
      { character: "1", style: "b" },
      { character: "1", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "Chart-italic" },
      { character: "W", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "g", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Pages 12–13. Why do you think cells divide? ",
    parentPageName: "3",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "1", style: "b" },
      { character: "2", style: "b" },
      { character: "EN_DASH", style: "b" },
      { character: "1", style: "b" },
      { character: "3", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "Sample-b" },
      { character: "W", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" }
    ]
  },
  {
    styleName: "Chart-subhd",
    content: "Cognates (English/Spanish)\nfor Essential Vocabulary\r",
    parentPageName: "3",
    characterStyles: [
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: ")", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "V", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "biosphere/la biósfera (page 6)\ncell/la célula (page 7)\nmeiosis/la meiosis (page 13)\r",
    parentPageName: "3",
    characterStyles: [
      { character: "b", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "ó", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ")", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "é", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "7", style: "[None]" },
      { character: ")", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: ")", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "membrane/la membrana (page 10)\nmitosis/la mitosis (page 12)\r",
    parentPageName: "3",
    characterStyles: [
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "0", style: "[None]" },
      { character: ")", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: ")", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "nucleus/el núcleo (page 10)\r",
    parentPageName: "3",
    characterStyles: [
      { character: "n", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "ú", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "0", style: "[None]" },
      { character: ")", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "organelle/el orgánulo (page 11)\r",
    parentPageName: "3",
    characterStyles: [
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "á", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: ")", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "protein/la proteína (page 10)",
    parentPageName: "3",
    characterStyles: [
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "í", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "0", style: "[None]" },
      { character: ")", style: "[None]" }
    ]
  }
];
 module.exports = paragraphData;
