const paragraphData = [
  {
    styleName: "A-hd",
    content: "Read Chapter 1 RI.6.2, SL.6.1, RST.6.2\r",
    parentPageName: "3",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "standards" },
      { character: "I", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "2", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "S", style: "standards" },
      { character: "L", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "1", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "R", style: "standards" },
      { character: "S", style: "standards" },
      { character: "T", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "2", style: "standards" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "If necessary, use the Scaffolded Preview and Cognates for Essential Vocabulary to help students access the text.  \r",
    parentPageName: "3",
    characterStyles: [
      { character: "I", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "g", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "V", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Read aloud the supporting question on page 6: How have Earth’s oceans evolved over time to attain their current defining features?\r",
    parentPageName: "3",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "6", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "H", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "w", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "v", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "E", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "v", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "v", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "v", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "f", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "g", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "f", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "?", style: "Italic" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Set a purpose. \r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "e", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: " ", style: "b" },
      { character: "p", style: "b" },
      { character: "u", style: "b" },
      { character: "r", style: "b" },
      { character: "p", style: "b" },
      { character: "o", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "b" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: As you read this chapter, you will use a strategy called Interactive Notes to help you understand how Earth’s oceans have evolved over time to attain their current defining features.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "g", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "N", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Display the Interactive Notes sample shown below. \r",
    parentPageName: "3",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "N", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: Interactive Notes is a form of note taking. Before you read a chapter, you’ll record your thoughts, text evidence, questions, and predictions in the “Before” column, and take notes in response in the “During” column. After you finish a section, you’ll summarize what you read by making judgments in the third column about the most important information in the text. The bottom of the chart provides space for you to summarize the entire chapter. \r",
    parentPageName: "3",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "N", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "B", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "D", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "f", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "j", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "g", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Preview pages 6–7 by reading the chapter title and headings and looking at the photos. Model how you use the “Before” column of the Interactive Notes to write your predictions and ideas about what you’ll read on these pages. Then read aloud the pages, and model how to complete the “During” column. Finally, in the “After” column, identify the most important points you read about. \r",
    parentPageName: "3",
    characterStyles: [
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "6", style: "" },
      { character: "EN_DASH", style: "" },
      { character: "7", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "B", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "N", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "D", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "A", style: "" },
      { character: "f", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Have students create an Interactive Notes chart on notebook paper, or distribute copies of BLM 1.\r",
    parentPageName: "3",
    characterStyles: [
      { character: "H", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "N", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "p", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "L", style: "" },
      { character: "M", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Instruct students to preview pages 8–9 and record thoughts, text evidence, key words, questions, and predictions in the “Before” column. Remind students to use these notes as they read the pages, and to react to the reading by taking notes in the “During” column. Finally, have students summarize by making judgments about what information is most important. Explain that making judgments about what we read helps us to better understand the text. Circulate to monitor and provide help as needed.  \r",
    parentPageName: "3",
    characterStyles: [
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "u", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "8", style: "" },
      { character: "EN_DASH", style: "" },
      { character: "9", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "B", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "D", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "j", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "g", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "x", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "j", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "g", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "c", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: " ", style: "" },
      { character: "", style: "" },
    ],
  },
];

module.exports = paragraphData;
