const paragraphData = [
  {
    styleName: "Chart-body-txt",
    content: "",
    parentPageName: "5",
    characterStyles: [{ character: "", style: "b" }],
  },
  {
    styleName: "Chart-hd",
    content: "Support for English Learners",
    parentPageName: "5",
    characterStyles: [
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "L", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
    ],
  },
  {
    styleName: "Chart-subhd",
    content: "Scaffolded Preview \nChapter 2\r",
    parentPageName: "5",
    characterStyles: [
      { character: "S", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "C", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "p", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "2", style: "b" },
    ],
  },
  {
    styleName: "Chart-body-txt",
    content:
      "Page 16. Who was Darwin? In this chapter, we’ll read about his theories on how species develop, adapt, and survive in their environments.\r",
    parentPageName: "5",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "1", style: "b" },
      { character: "6", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "" },
      { character: "W", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "D", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "I", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: ",", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: ",", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: ",", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
    ],
  },
  {
    styleName: "Chart-body-txt",
    content:
      "Page 19. Why do you think the author includes a sidebar about breeding a dachshund in this book about adaptations? Think about what dachshunds can do because of their size and shape.\r",
    parentPageName: "5",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "1", style: "b" },
      { character: "9", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "" },
      { character: "W", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "g", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "T", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "z", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
    ],
  },
  {
    styleName: "Chart-body-txt",
    content: "Chapter 3\r",
    parentPageName: "5",
    characterStyles: [
      { character: "C", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "p", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "3", style: "b" },
    ],
  },
  {
    styleName: "Chart-body-txt",
    content:
      "Page 28. Look at the illustration of the dinosaurs. We’ll read what happens to organisms, such as dinosaurs, when they don’t adapt.",
    parentPageName: "5",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "2", style: "b" },
      { character: "8", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "" },
      { character: "L", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "W", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "g", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ",", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ",", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
    ],
  },
  {
    styleName: "Chart-subhd",
    content: "Cognates (English/Spanish)\nfor Essential Vocabulary\r",
    parentPageName: "5",
    characterStyles: [
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "g", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "E", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "/", style: "" },
      { character: "S", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: ")", style: "" },
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "V", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "evolution/la evolución (page 19)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "/", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "ó", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: "9", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "fossil/el fósil (page 17)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "/", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "ó", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: "7", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "natural selection/la selección natural (page 21)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "/", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "ó", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "1", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "carnivore/el carnívoro (page 26)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "/", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "í", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "6", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "convergent evolution/la evolución convergente (page 28)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "/", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "ó", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "8", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "divergent evolution/la evolución divergente (page 27)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "/", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "ó", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "7", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "herbivore/el herbívoro (page 26)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "/", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "b", style: "" },
      { character: "í", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "6", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "mammal/el mamífero (page 29)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "/", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "í", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "9", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "niche/el nicho (page 28)\r",
    parentPageName: "5",
    characterStyles: [
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "/", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "8", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "trilobite/el trilobita (page 25)",
    parentPageName: "5",
    characterStyles: [
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "/", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "5", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Chart-subhd",
    content: "Sentence Frames to Support Collaborative Conversation\r",
    parentPageName: "5",
    characterStyles: [
      { character: "S", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "Based on my notes, I know that natural selection is _____.\r",
    parentPageName: "5",
    characterStyles: [
      { character: "B", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "d", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "m", style: "Sidebar-ital" },
      { character: "y", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: ",", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "I", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "k", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "w", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "h", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "u", style: "Sidebar-ital" },
      { character: "r", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "l", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "l", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "c", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "i", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "i", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: ".", style: "Sidebar-ital" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "Based on my notes, I know that extinction happens when _____.\r",
    parentPageName: "5",
    characterStyles: [
      { character: "B", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "d", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "m", style: "Sidebar-ital" },
      { character: "y", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: ",", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "I", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "k", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "w", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "h", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "x", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "i", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "c", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "i", style: "Sidebar-ital" },
      { character: "o", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "h", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "p", style: "Sidebar-ital" },
      { character: "p", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "w", style: "Sidebar-ital" },
      { character: "h", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: ".", style: "Sidebar-ital" },
    ],
  },
  {
    styleName: "Sidebar-body-txt",
    content: "The chapters’ central ideas are _____ and _____.",
    parentPageName: "5",
    characterStyles: [
      { character: "T", style: "Sidebar-ital" },
      { character: "h", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "c", style: "Sidebar-ital" },
      { character: "h", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "p", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "r", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "c", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "t", style: "Sidebar-ital" },
      { character: "r", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "l", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "i", style: "Sidebar-ital" },
      { character: "d", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "s", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "r", style: "Sidebar-ital" },
      { character: "e", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "a", style: "Sidebar-ital" },
      { character: "n", style: "Sidebar-ital" },
      { character: "d", style: "Sidebar-ital" },
      { character: " ", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: "_", style: "Sidebar-ital" },
      { character: ".", style: "Sidebar-ital" },
    ],
  },
];
module.exports = paragraphData;
