let Y63063_TG_G6_U2 = {
  "tables": [
    "<table><thead><tr><th>What Makes This Text Complex?</th></tr></thead><tbody><tr><td><p><span>Purpose and Levels <br>of Meaning <br></span><span><span>4</span></span></p></td><td><p><span>Themes are multidimensional and require readers to make inferences about characters and plot events. (pp. 5–9)</span><span>★</span></p></td></tr><tr><td><p><span>Structure <br></span><span><span>4</span></span></p></td><td><p><span>The book is intricate with regard to text types and modes of communication. Sections include informational texts, excerpts from authentic literature, and essays. (pp. 2–9)</span><span>★</span></p></td></tr><tr><td><p><span>Language Conventionality and Clarity <br></span><span><span>2</span></span></p></td><td><p><span>The text includes complex sentence structure, rich descriptive language, and a range of literary techniques. (p. 10)</span><span>★</span></p></td></tr><tr><td><p><span>Knowledge <br>Demands <br></span><span><span>2</span></span></p></td><td><p><span>Some readers may not be familiar with certain historical and geographical settings.</span></p></td></tr></tbody></table>",
    "<table><thead><tr><th>Key Events</th></tr></thead><tbody><tr><td><p><span>Bud goes to the library to look at a book of maps describing the distances between cities.</span></p></td></tr><tr><td><p><span>He plans to travel 120 miles from Flint to Grand Rapids to find his father.</span></p></td></tr><tr><td><p><span>The librarian gives him a Civil War book, and he reads it all day.</span></p></td></tr><tr><td><p><span>He begins his journey to Grand Rapids as soon as the library closed.</span></p></td></tr><tr><td><p><span>When he arrives, Calloway denies being his father. They later learn he is Bud’s grandfather, and Bud has been reunited with his family after all.</span></p></td></tr></tbody></table>",
    "<table><thead><tr><th>Bud goes to the library to look at a book that gives information about the distances between different cities. This will help him plan his journey to Grand Rapids where he will search for his father. He will start the 120-mile journey that day. After reading all day, he begins his journey. When he arrives in Grand Rapids, Calloway denies being his father, but the band takes Bud in. He finally realizes Calloway is his grandfather, and he has found his family after all.</th></tr></thead><tbody></tbody></table>",
    "<table><thead><tr><th>Key Events</th></tr></thead><tbody><tr><td><p><span>M.C. is sitting on his steel pole, examining the valley below and Sarah’s Mountain.</span></p></td></tr><tr><td><p><span>He “sees” visions of his family long ago, how they lived in this region, and died here.</span></p></td></tr><tr><td><p><span>His great-grandmother’s escape from slavery in the area helps him realize how important the mountain and the region are to his family.</span></p></td></tr><tr><td><p><span>Now he realizes that the same area brings different hardships to his family because of the strip miners damaging the landscape.</span></p></td></tr><tr><td><p><span>He sees his brothers and sisters enjoying the area, and he keeps an eye on them as he was meant to, from on top of his steel pole.</span></p></td></tr></tbody></table>",
    "<table><thead><tr><th>M.C. sits on top of a tall steel pole and overlooks Sarah’s Mountain, a place his family has lived for generations. As he is up there looking at the beautiful scenery, he thinks about the history of the land and how many family members lived and died there. He thinks of his great-grandmother, who escaped slavery with a tiny baby and faced hard times during her lifetime. He worries the strip miners who have set themselves up on the mountain will destroy the future of this mountain for him and his brothers and sisters, whom he watches below.</th></tr></thead><tbody></tbody></table>",
    "<table><thead><tr><th></th><th>“Characters Escape to Cope”</th><th>“Characters Become Observers”</th><th>“Characters Defined by Environment”</th></tr></thead><tbody><tr><td><p><span>Opinion</span></p></td><td><p><span>Both main characters rely on their imaginations to escape harsh realities.</span></p></td><td><p><span>Both main characters are astute observers who examine and reflect on their own world.</span></p></td><td><p><span>Both main characters are a product of their environments.</span></p></td></tr><tr><td><p><span>Reason 1</span></p></td><td><p><span>Bud has a “pretend” family on the food line to make him cope with being alone.</span></p></td><td><p><span>Observation is so important to M.C. that he has a steel pole devoted to observing.</span></p></td><td><p><span>M.C. spends time daydreaming because he lives in a time before technology.</span></p></td></tr><tr><td><p><span>Reason 2</span></p></td><td><p><span>He escapes into his imagination at the library, not realizing he spent all day reading a book.</span></p></td><td><p><span>Bud carefully calculates how long it will take him to walk from Flint to Grand Rapids.</span></p></td><td><p><span>He acts responsibly because he is the eldest and is expected to take care of his siblings.</span></p></td></tr><tr><td><p><span>Reason 3</span></p></td><td><p><span>M.C. uses his time on the steel pole to escape his current worries and imagines a world he never lived through—when his great-grandmother escaped slavery.</span></p></td><td><p><span>Bud observes a Civil War book in such detail that he does not realize that a whole afternoon has passed.</span></p></td><td><p><span>Growing up during the Great Depression makes Bud’s character resourceful, polite, and hardworking.</span></p></td></tr></tbody></table>",
    "<table><thead><tr><th>Text Evidence</th></tr></thead><tbody><tr><td><p><span>“One second I was opening the first page of the book . . . and the next second the librarian was standing over me . . .” (p. 7)</span></p></td></tr><tr><td><p><span>“I am very impressed, you really devoured that book, didn’t you? But it’s time to close now . . .” (p. 7)</span></p></td></tr><tr><td><p><span>“I couldn’t believe it, it’s happened again! I’d spent the whole day reading.” (p. 7)</span></p></td></tr><tr><td><p><span><img alt=\"\" src=\"Y63063_TG_G6_U2-web-resources/image/1.png\"></span></p></td></tr><tr><td><p><span>Conclusion</span></p></td></tr><tr><td><p><span>Bud has a thirst for knowledge and enjoys learning.</span></p></td></tr></tbody></table>",
    "<table><thead><tr><th>When Bud is in the library, he says, “It seems like time flies when you’re in one.” What does Bud mean by this, and what does it tell you about him?</th></tr></thead><tbody></tbody></table>",
    "<table><thead><tr><th>Why is Sarah’s Mountain so important to M.C. Higgins?</th></tr></thead><tbody></tbody></table>",
    "<table><thead><tr><th>Text Evidence</th></tr></thead><tbody><tr><td><p>“M.C. shuddered at the thought of all the dead on the mountain, under the junk around his pole.” (p. 12)</p></td></tr><tr><td><p>“M.C. knew the story by heart. He knew she ran for freedom. She carried a baby.” (p. 12<span>)</span></p></td></tr><tr><td><p>“But the idea nagged at him, worrying him, that a hundred years of the past seeped out of the hills to surround him.” (p. 13)</p></td></tr><tr><td><p>“Laughter was coming from there. His brothers and sister had just reached the lake.” (p. 15)</p></td></tr><tr><td><p><span><img alt=\"\" src=\"Y63063_TG_G6_U2-web-resources/image/1.png\"></span></p></td></tr><tr><td><p><span>Conclusion</span></p></td></tr><tr><td><p>The mountain is a place of great beauty, and it is part of his family’s history.</p></td></tr></tbody></table>",
    "<table><thead><tr><th>Text Evidence</th></tr></thead><tbody><tr><td><p><span>“That meant I’d have to walk for twenty-four hours to reach Grand Rapids.” (p. 6)</span></p></td></tr><tr><td><p><span>“I figured it would be easiest to do the night part first. . . . I wrote down all the names of the cities I’d have to pass through to get there.” (p. 6)</span></p></td></tr><tr><td><p><span>“I’m old now, but I can still get around. Never did leave the mountain. None of the others did, either.” (p. 12)</span></p></td></tr><tr><td><p><span>“Suddenly he was aware of the deep whine of machines in the hills behind Sarah’s to the north.” (p. 13)</span></p></td></tr><tr><td><p><span><img alt=\"\" src=\"Y63063_TG_G6_U2-web-resources/image/1.png\"></span></p></td></tr><tr><td><p><span>Inference</span></p></td></tr><tr><td><p><span>Bud’s determined actions help the reader understand how important finding his father is, while M.C.’s dreaminess helps the reader understand the importance of saving the mountain.</span></p></td></tr></tbody></table>",
    "<table><thead><tr><th>How are the points of view different in the selections? Explain how this difference affects the reader’s understanding of events in each story.</th></tr></thead><tbody></tbody></table>",
    "<table><thead><tr><th>Opinion:</th></tr></thead><tbody><tr><td><p><span>Reason</span></p></td><td><p><span>Text Evidence</span></p></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr></tbody></table>"
  ]
};

module.exports = {
    Y63063_TG_G6_U2,
};