const paragraphData = [
  {
    styleName: "A-hd",
    content: "Read Chapter 4 and Conclusion RI.6.2, RST.6.2\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "4", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "standards" },
      { character: "I", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "2", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "R", style: "standards" },
      { character: "S", style: "standards" },
      { character: "T", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "2", style: "standards" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "If necessary, use the Scaffolded Preview and Cognates for Essential Vocabulary to help students access the text. \r",
    parentPageName: "6",
    characterStyles: [
      { character: "I", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "g", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "V", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Read aloud the supporting question on page 34: How do animals, plants, and humans interact?\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "3", style: "" },
      { character: "4", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "H", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "w", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: ",", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "p", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: ",", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "?", style: "Italic" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Set a purpose for the first read. \r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "e", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: " ", style: "b" },
      { character: "p", style: "b" },
      { character: "u", style: "b" },
      { character: "r", style: "b" },
      { character: "p", style: "b" },
      { character: "o", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "f", style: "b" },
      { character: "o", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "f", style: "b" },
      { character: "i", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "r", style: "b" },
      { character: "e", style: "b" },
      { character: "a", style: "b" },
      { character: "d", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "teacher-talk bold" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: As you read this chapter, continue using the Double Entry Journal to focus on how animals, plants, and humans interact. Then we’ll collaborate to identify the most important questions and answers in order to summarize the key concepts of this chapter.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "A", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "D", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "E", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "J", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "SINGLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "q", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "z", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Have students create a Double Entry Journal on notebook paper, or distribute copies of BLM 1.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "H", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "J", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "p", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "L", style: "" },
      { character: "M", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Review the note-taking process as needed.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "-", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Choose the reading option that best meets the needs of your students. \r",
    parentPageName: "6",
    characterStyles: [
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Summarize Key Concepts: Think and Write Independently\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "K", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "B-subhd" },
      { character: "h", style: "B-subhd" },
      { character: "i", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "k", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "a", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "W", style: "B-subhd" },
      { character: "r", style: "B-subhd" },
      { character: "i", style: "B-subhd" },
      { character: "t", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "I", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "p", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "t", style: "B-subhd" },
      { character: "l", style: "B-subhd" },
      { character: "y", style: "B-subhd" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Give students a few moments to review their Double Entry Journals to identify the information that best enables them to summarize the key points in this chapter.  \r",
    parentPageName: "6",
    characterStyles: [
      { character: "G", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "J", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Use the Sentence Frames to Support Collaborative Conversation for English learners.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "U", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Bring students together, and ask several volunteers to read their summaries aloud. As a whole group, evaluate the summaries and identify any key information that was omitted. As needed, clarify students’ understanding of the supporting question.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "B", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "As a group, construct a written summary of the key ideas in the chapter.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "u", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Reread the summary that your class has collaborated to write.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "6",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Label",
    content: "\nSample Summary (Chapter 4/Conclusion)\r",
    parentPageName: "6",
    characterStyles: [
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "S", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "4", style: "" },
      { character: "/", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ")", style: "" },
    ],
  },
  {
    styleName: "Label",
    content: "\r",
    parentPageName: "6",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Sample-body-txt",
    content:
      "Living organisms within a habitat interact with one another. Some organisms compete, others prey upon one another, and still others depend on one another for their survival. The varying relationships lead to biodiversity, which is essential to the future of life on Earth.",
    parentPageName: "6",
    characterStyles: [
      { character: "L", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "p", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "y", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: ".", style: "" },
    ],
  },
];
module.exports = paragraphData;
