const paragraphData = [teacher-talkteacher-talk
  {
    styleName: "Lesson_A-hd",
    content: "Read An Attack on the Mayflower in the Year 2647, pages 18–22 \nRL.6.2\r",
    parentPageName: "4",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "b-ital" },
      { character: "n", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "A", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: "a", style: "b-ital" },
      { character: "c", style: "b-ital" },
      { character: "k", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "o", style: "b-ital" },
      { character: "n", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: "h", style: "b-ital" },
      { character: "e", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "M", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "b-ital" },
      { character: "i", style: "b-ital" },
      { character: "n", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: "h", style: "b-ital" },
      { character: "e", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "Y", style: "b-ital" },
      { character: "e", style: "b-ital" },
      { character: "a", style: "b-ital" },
      { character: "r", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "2", style: "b-ital" },
      { character: "6", style: "b-ital" },
      { character: "4", style: "b-ital" },
      { character: "7", style: "b-ital" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "8", style: "[None]" },
      { character: "EN_DASH", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "R", style: "CC-code" },
      { character: "L", style: "CC-code" },
      { character: ".", style: "CC-code" },
      { character: "6", style: "CC-code" },
      { character: ".", style: "CC-code" },
      { character: "2", style: "CC-code" }
    ]
  },
  {
    styleName: "Lesson_A-hd",
    content: "Set a Purpose\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: As you read pages 18–22 of An Attack on the Starship Mayflower in the Year 2647, use self-stick notes to flag key story elements—characters, setting, and main events. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "a", style: "b" },
      { character: "y", style: "b" },
      { character: ":", style: "b" },
      { character: " ", style: "b" },
      { character: "A", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "y", style: "b" },
      { character: "o", style: "b" },
      { character: "u", style: "b" },
      { character: " ", style: "b" },
      { character: "r", style: "b" },
      { character: "e", style: "b" },
      { character: "a", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "p", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "1", style: "b" },
      { character: "8", style: "b" },
      { character: "EN_DASH", style: "b" },
      { character: "2", style: "b" },
      { character: "2", style: "b" },
      { character: " ", style: "b" },
      { character: "o", style: "b" },
      { character: "f", style: "b" },
      { character: " ", style: "b" },
      { character: "A", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "A", style: "b" },
      { character: "t", style: "b" },
      { character: "t", style: "b" },
      { character: "a", style: "b" },
      { character: "c", style: "b" },
      { character: "k", style: "b" },
      { character: " ", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "S", style: "b" },
      { character: "t", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: "h", style: "b" },
      { character: "i", style: "b" },
      { character: "p", style: "b" },
      { character: " ", style: "b" },
      { character: "M", style: "i" },
      { character: "a", style: "i" },
      { character: "y", style: "i" },
      { character: "f", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "Y", style: "b" },
      { character: "e", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "2", style: "b" },
      { character: "6", style: "b" },
      { character: "4", style: "b" },
      { character: "7", style: "b" },
      { character: ",", style: "b" },
      { character: " ", style: "b" },
      { character: "u", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: "l", style: "b" },
      { character: "f", style: "b" },
      { character: "-", style: "b" },
      { character: "s", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "c", style: "b" },
      { character: "k", style: "b" },
      { character: " ", style: "b" },
      { character: "n", style: "b" },
      { character: "o", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "o", style: "b" },
      { character: " ", style: "b" },
      { character: "f", style: "b" },
      { character: "l", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: " ", style: "b" },
      { character: "k", style: "b" },
      { character: "e", style: "b" },
      { character: "y", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "t", style: "b" },
      { character: "o", style: "b" },
      { character: "r", style: "b" },
      { character: "y", style: "b" },
      { character: " ", style: "b" },
      { character: "e", style: "b" },
      { character: "l", style: "b" },
      { character: "e", style: "b" },
      { character: "m", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "t", style: "b" },
      { character: "s", style: "b" },
      { character: "EM_DASH", style: "b" },
      { character: "c", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "a", style: "b" },
      { character: "c", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: ",", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: "t", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: "g", style: "b" },
      { character: ",", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "m", style: "b" },
      { character: "a", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "e", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "t", style: "b" },
      { character: "s", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "b" }
    ]
  },
  {
    styleName: "table_label",
    content: "Choose the reading option that best meets your students’ needs. If students need more support to access the text, use the Scaffolded Preview provided.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "C", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "SINGLE_RIGHT_QUOTE", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Summarize Key Story Elements: Think and Write Independently\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "K", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "W", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "y", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Invite students to share with a partner what they noted in the text. Have them collaborate to create a new Story Elements chart for pages 18–22 of An Attack on the Starship Mayflower in the Year 2647. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "8", style: "[None]" },
      { character: "EN_DASH", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "A", style: "i" },
      { character: "t", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "c", style: "i" },
      { character: "k", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "S", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "s", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "p", style: "i" },
      { character: " ", style: "i" },
      { character: "M", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "Y", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "2", style: "i" },
      { character: "6", style: "i" },
      { character: "4", style: "i" },
      { character: "7", style: "i" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "", style: "[None]" }
    ]
  },
  {
    styleName: "table_label",
    content: "Sample Key Story Elements Chart \r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "labels" },
      { character: "a", style: "labels" },
      { character: "m", style: "labels" },
      { character: "p", style: "labels" },
      { character: "l", style: "labels" },
      { character: "e", style: "labels" },
      { character: " ", style: "labels" },
      { character: "K", style: "labels" },
      { character: "e", style: "labels" },
      { character: "y", style: "labels" },
      { character: " ", style: "labels" },
      { character: "S", style: "labels" },
      { character: "t", style: "labels" },
      { character: "o", style: "labels" },
      { character: "r", style: "labels" },
      { character: "y", style: "labels" },
      { character: " ", style: "labels" },
      { character: "E", style: "labels" },
      { character: "l", style: "labels" },
      { character: "e", style: "labels" },
      { character: "m", style: "labels" },
      { character: "e", style: "labels" },
      { character: "n", style: "labels" },
      { character: "t", style: "labels" },
      { character: "s", style: "labels" },
      { character: " ", style: "labels" },
      { character: "C", style: "labels" },
      { character: "h", style: "labels" },
      { character: "a", style: "labels" },
      { character: "r", style: "labels" },
      { character: "t", style: "labels" },
      { character: " ", style: "labels" }
    ]
  },
  {
    styleName: "table_label",
    content: "\r",
    parentPageName: "4",
    characterStyles: [
    ]
  },
  {
    styleName: "table_label",
    content: "Next, have pairs collaborate to write their own summary of An Attack on the Starship Mayflower in the Year 2647. If students need more support in deciding what to include in a summary, refer back to the lesson strategy taught in Part 1. Bring students together and ask several pairs to read their summaries aloud. As a group, evaluate the summaries and identify any key details that were omitted. Then work as a group to construct a \nwritten summary of the first half of the story.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "N", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "A", style: "i" },
      { character: "t", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "c", style: "i" },
      { character: "k", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "S", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "s", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "p", style: "i" },
      { character: " ", style: "i" },
      { character: "M", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "Y", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "2", style: "i" },
      { character: "6", style: "i" },
      { character: "4", style: "i" },
      { character: "7", style: "i" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "B", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "table_label",
    content: "\r",
    parentPageName: "4",
    characterStyles: [
      { character: "", style: "[None]" }
    ]
  },
  {
    styleName: "table_label",
    content: "Sample Summary",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "labels" },
      { character: "a", style: "labels" },
      { character: "m", style: "labels" },
      { character: "p", style: "labels" },
      { character: "l", style: "labels" },
      { character: "e", style: "labels" },
      { character: " ", style: "labels" },
      { character: "S", style: "labels" },
      { character: "u", style: "labels" },
      { character: "m", style: "labels" },
      { character: "m", style: "labels" },
      { character: "a", style: "labels" },
      { character: "r", style: "labels" },
      { character: "y", style: "labels" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Characters",
    parentPageName: "4",
    characterStyles: [
      { character: "C", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "a", style: "b" },
      { character: "c", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Settings",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "e", style: "b" },
      { character: "t", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: "g", style: "b" },
      { character: "s", style: "b" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Ace, Helvetica, Captain Trace ",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "H", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "C", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "T", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "On the Starship Mayflower in 2647",
    parentPageName: "4",
    characterStyles: [
      { character: "O", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "S", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "2", style: "Character Style 1" },
      { character: "6", style: "Character Style 1" },
      { character: "4", style: "Character Style 1" },
      { character: "7", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Main Events\r",
    parentPageName: "4",
    characterStyles: [
      { character: "M", style: "b" },
      { character: "a", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "E", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "t", style: "b" },
      { character: "s", style: "b" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Ace is jealous of his sister Helvetica’s heroic stories. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "j", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "H", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "The Mayflower, where they live, is attacked. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "T", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "i" },
      { character: "a", style: "i" },
      { character: "y", style: "i" },
      { character: "f", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Helvetica and Captain Trace put on their battle armor and prepare to fight. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "H", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "C", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "T", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Ace is too young to fight. \r",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "It is one of the worst attacks on the Mayflower. ",
    parentPageName: "4",
    characterStyles: [
      { character: "I", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "i" },
      { character: "a", style: "i" },
      { character: "y", style: "i" },
      { character: "f", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Ace is jealous of his sister Helvetica’s heroic stories. That night, the Mayflower is attacked. Helvetica and Captain Trace put on their battle armor and prepare to defend their home. Ace is too young to fight, so he joins the other children and people who cannot go into battle. It is one of the worst attacks on the Mayflower that Ace has seen. ",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "j", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "H", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "T", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "i" },
      { character: "a", style: "i" },
      { character: "y", style: "i" },
      { character: "f", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "H", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "C", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "T", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "A", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "j", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "I", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "i" },
      { character: "a", style: "i" },
      { character: "y", style: "i" },
      { character: "f", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "A", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  }
];
 module.exports = paragraphData;
