const paragraphData = [
  {
    styleName: "A-hd",
    content:
      "Close Reading Option 4: Answer Text Evidence Questions RI.6.1, RI.6.2, RI.6.4, RST.6.1\r",
    parentPageName: "10",
    characterStyles: [
      { character: "C", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "4", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "s", style: "A-subhd" },
      { character: "w", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "r", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "T", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "x", style: "A-subhd" },
      { character: "t", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "E", style: "A-subhd" },
      { character: "v", style: "A-subhd" },
      { character: "i", style: "A-subhd" },
      { character: "d", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "c", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "Q", style: "A-subhd" },
      { character: "u", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "s", style: "A-subhd" },
      { character: "t", style: "A-subhd" },
      { character: "i", style: "A-subhd" },
      { character: "o", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "s", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "R", style: "standards" },
      { character: "I", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "1", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "R", style: "standards" },
      { character: "I", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "2", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "R", style: "standards" },
      { character: "I", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "4", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "R", style: "standards" },
      { character: "S", style: "standards" },
      { character: "T", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "1", style: "standards" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Draw and Support Inferences\r",
    parentPageName: "10",
    characterStyles: [
      { character: "D", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Display and read aloud the close reading question.\r",
    parentPageName: "10",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "10",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Text Evidence: “Scientists believe that long ago, these projectiles regularly smashed into Earth’s surface, dumping huge quantities of ice when they landed. This material vaporized instantly due to Earth’s blistering temperature and joined the gases already circling our planet.” (p. 6) RI.6.1\r",
    parentPageName: "10",
    characterStyles: [
      { character: "T", style: "b" },
      { character: "e", style: "b" },
      { character: "x", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "E", style: "b" },
      { character: "v", style: "b" },
      { character: "i", style: "b" },
      { character: "d", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "e", style: "b" },
      { character: ":", style: "b" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "S", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "o", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "j", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "f", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "j", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "6", style: "" },
      { character: ")", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "I", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "1", style: "" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Identify and Determine Central Idea and Key Details\r",
    parentPageName: "10",
    characterStyles: [
      { character: "I", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "K", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Display and read aloud the close reading question.\r",
    parentPageName: "10",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "10",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Text Evidence: “As Earth’s plates continue their perpetual drift, the Atlantic Ocean will continue to widen, and the Pacific Ocean will continue to narrow. Millions of years from now, our planet and its seas will look very different than they do today.” (p. 9) RI.6.2\r",
    parentPageName: "10",
    characterStyles: [
      { character: "T", style: "b" },
      { character: "e", style: "b" },
      { character: "x", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "E", style: "b" },
      { character: "v", style: "b" },
      { character: "i", style: "b" },
      { character: "d", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "e", style: "b" },
      { character: ":", style: "b" },
      { character: " ", style: "b" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "t", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "9", style: "" },
      { character: ")", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "I", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "2", style: "" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Determine Word Meaning\r",
    parentPageName: "10",
    characterStyles: [
      { character: "D", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Display and read aloud the close reading questions.\r",
    parentPageName: "10",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "10",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Definition: a regular change in sea level caused by the gravitational pull of the moon and sun\r",
    parentPageName: "10",
    characterStyles: [
      { character: "D", style: "b" },
      { character: "e", style: "b" },
      { character: "f", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: "i", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: ":", style: "b" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Text Evidence: “The ocean rises and falls each day in regular patterns called tides.” \n(p. 19) RI.6.4\r",
    parentPageName: "10",
    characterStyles: [
      { character: "T", style: "b" },
      { character: "e", style: "b" },
      { character: "x", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "E", style: "b" },
      { character: "v", style: "b" },
      { character: "i", style: "b" },
      { character: "d", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "e", style: "b" },
      { character: ":", style: "b" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: "9", style: "" },
      { character: ")", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "I", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "4", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "10",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Find text evidence to support the inference that comets and meteors may have contributed to the formation of Earth’s atmosphere. ",
    parentPageName: "10",
    characterStyles: [
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Find text evidence that supports the claim on page 9 that Earth’s oceans will not keep their familiar shapes forever.",
    parentPageName: "10",
    characterStyles: [
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "9", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "How is the word tides used in this book? What clues help the reader understand the meaning of the word?",
    parentPageName: "10",
    characterStyles: [
      { character: "H", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "b" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: "?", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: "?", style: "" },
    ],
  },
];
module.exports = paragraphData;
