const paragraphData = [teacher-talkteacher-talkteacher-talk
  {
    styleName: "Lesson_A-hd",
    content: "Build Language and Vocabulary\r",
    parentPageName: "11",
    characterStyles: [
      { character: "B", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "V", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Extend Language Concepts: Imperatives L.6.1\r",
    parentPageName: "11",
    characterStyles: [
      { character: "E", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "1", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Read the following sentence from page 7:\r",
    parentPageName: "11",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "7", style: "[None]" },
      { character: ":", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "“Think of a place that is very hot and dry.”\r",
    parentPageName: "11",
    characterStyles: [
      { character: "DOUBLE_LEFT_QUOTE", style: "Italic" },
      { character: "T", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "k", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "f", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "p", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "v", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "y", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "y", style: "Italic" },
      { character: ".", style: "Italic" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "Italic" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say:  This sentence is an imperative because it instructs readers to do something.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Imperative sentences give commands or instructions, and they almost never have a subject because they address the reader directly. In this sentence, the author commands students to “think of a place that is very hot and dry.”   Have students work in pairs to look through the book for additional examples of imperatives. Ask students to share their findings. Monitor and provide feedback as necessary. Record the imperatives on a chart to refer to throughout the rest of the unit.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "DOUBLE_LEFT_QUOTE", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "M", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Turn and talk. Challenge partners to compose sentences with different imperatives based on information in the text. Have partners share their sentences with the rest of the class and explain how the imperatives affect their sentences.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "T", style: "b" },
      { character: "u", style: "b" },
      { character: "r", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "a", style: "b" },
      { character: "l", style: "b" },
      { character: "k", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Extend Language Concepts: Conjunctions (but) L.6.1\r",
    parentPageName: "11",
    characterStyles: [
      { character: "E", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ")", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "1", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Read the following sentences from page 13:\r",
    parentPageName: "11",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: ":", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_C-hd",
    content: "“St. Louis, Missouri is far south of Juneau but has colder winters.”\r",
    parentPageName: "11",
    characterStyles: [
      { character: "DOUBLE_LEFT_QUOTE", style: "Italic" },
      { character: "S", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: ".", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "L", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: ",", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "M", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "f", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "f", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "J", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "b", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "w", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: ".", style: "Italic" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "Italic" }
    ]
  },
  {
    styleName: "Lesson_C-hd",
    content: "\r",
    parentPageName: "11",
    characterStyles: [
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: A conjunction is a word that connects two ideas. The word but is a conjunction that shows opposite or contrasting ideas. In this sentence, for example, the conjunction but contrasts the climate of St. Louis, Missouri and Juneau, Alaska.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "b-ital" },
      { character: "u", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "b-ital" },
      { character: "u", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "M", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "J", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Read the following sentence from page 24:\r",
    parentPageName: "11",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: "4", style: "[None]" },
      { character: ":", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "“Estivation is similar to hibernation, but it occurs in the summer.”\r",
    parentPageName: "11",
    characterStyles: [
      { character: "DOUBLE_LEFT_QUOTE", style: "Italic" },
      { character: "E", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "v", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "l", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "b", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: ",", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "b", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: ".", style: "Italic" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "Italic" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: In this sentence, the conjunction but contrasts estivation and hibernation.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "b-ital" },
      { character: "u", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Have students work in pairs to find more examples of the conjunction but as it’s used to contrast. Have them list the sentences in which the conjunction is used. As students share their findings, record them on chart paper under the title “Examples of Conjunctions.”",
    parentPageName: "11",
    characterStyles: [
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "Italic" },
      { character: "u", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "SINGLE_RIGHT_QUOTE", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "DOUBLE_LEFT_QUOTE", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "j", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "[None]" }
    ]
  }
];
 module.exports = paragraphData;
