const paragraphData = [teacher-talkteacher-talk
  {
    styleName: "Lesson_A-hd",
    content: "Read Part 1 (pp. 2–9) RL.6.1, RL.6.3, W.6.5, W.6.8, SL.6.1a, SL.6.1b, SL.6.1c, SL.6.1d\r",
    parentPageName: "2",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: " ", style: "" },
      { character: "(", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "EN_DASH", style: "" },
      { character: "9", style: "" },
      { character: ")", style: "" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "R", style: "Lesson_A-hd-standards" },
      { character: "L", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "1", style: "Lesson_A-hd-standards" },
      { character: ",", style: "Lesson_A-hd-standards" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "R", style: "Lesson_A-hd-standards" },
      { character: "L", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "3", style: "Lesson_A-hd-standards" },
      { character: ",", style: "Lesson_A-hd-standards" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "W", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "5", style: "Lesson_A-hd-standards" },
      { character: ",", style: "Lesson_A-hd-standards" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "W", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "8", style: "Lesson_A-hd-standards" },
      { character: ",", style: "Lesson_A-hd-standards" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "S", style: "Lesson_A-hd-standards" },
      { character: "L", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "1", style: "Lesson_A-hd-standards" },
      { character: "a", style: "Lesson_A-hd-standards" },
      { character: ",", style: "Lesson_A-hd-standards" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "S", style: "Lesson_A-hd-standards" },
      { character: "L", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "1", style: "Lesson_A-hd-standards" },
      { character: "b", style: "Lesson_A-hd-standards" },
      { character: ",", style: "Lesson_A-hd-standards" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "S", style: "Lesson_A-hd-standards" },
      { character: "L", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "1", style: "Lesson_A-hd-standards" },
      { character: "c", style: "Lesson_A-hd-standards" },
      { character: ",", style: "Lesson_A-hd-standards" },
      { character: " ", style: "Lesson_A-hd-standards" },
      { character: "S", style: "Lesson_A-hd-standards" },
      { character: "L", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "6", style: "Lesson_A-hd-standards" },
      { character: ".", style: "Lesson_A-hd-standards" },
      { character: "1", style: "Lesson_A-hd-standards" },
      { character: "d", style: "Lesson_A-hd-standards" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Preview and Make Predictions\r",
    parentPageName: "2",
    characterStyles: [
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Invite students to flip through the book and view the illustrations, or display the e-book and preview the pages together.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "-", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Read aloud the features of an analytical argument on the inside front cover. Then have students turn to the Table of Contents and read the titles of each section. Invite students to read the book description on the back cover.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "c", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: Two of the stories in this book are historical fiction. Although the main characters are not real people, the events in these stories are based on true events. The third story is an example of realistic fiction. It is set in the present-day. The characters are made-up, but the situation is something that could happen. After the three stories, there are three argument essays about courage.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "l", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "o", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "-", style: "" },
      { character: "d", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "-", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "f", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "If your students need more support, use the Scaffolded Preview provided.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "I", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Set a Purpose\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: Because these stories deal with characters who make difficult decisions that affect themselves and others, let’s pay close attention to how their actions contribute to the sequence of events. As you read “Into the Fire,” use self-stick notes to identify the main characters and setting, and to flag main ideas.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "f", style: "" },
      { character: "-", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Choose the reading option that best meets your students’ needs.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Summarize Main Idea and Key Details: Think and Write Together\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "K", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "Lesson_B-hd-LightFace" },
      { character: "h", style: "Lesson_B-hd-LightFace" },
      { character: "i", style: "Lesson_B-hd-LightFace" },
      { character: "n", style: "Lesson_B-hd-LightFace" },
      { character: "k", style: "Lesson_B-hd-LightFace" },
      { character: " ", style: "Lesson_B-hd-LightFace" },
      { character: "a", style: "Lesson_B-hd-LightFace" },
      { character: "n", style: "Lesson_B-hd-LightFace" },
      { character: "d", style: "Lesson_B-hd-LightFace" },
      { character: " ", style: "Lesson_B-hd-LightFace" },
      { character: "W", style: "Lesson_B-hd-LightFace" },
      { character: "r", style: "Lesson_B-hd-LightFace" },
      { character: "i", style: "Lesson_B-hd-LightFace" },
      { character: "t", style: "Lesson_B-hd-LightFace" },
      { character: "e", style: "Lesson_B-hd-LightFace" },
      { character: " ", style: "Lesson_B-hd-LightFace" },
      { character: "T", style: "Lesson_B-hd-LightFace" },
      { character: "o", style: "Lesson_B-hd-LightFace" },
      { character: "g", style: "Lesson_B-hd-LightFace" },
      { character: "e", style: "Lesson_B-hd-LightFace" },
      { character: "t", style: "Lesson_B-hd-LightFace" },
      { character: "h", style: "Lesson_B-hd-LightFace" },
      { character: "e", style: "Lesson_B-hd-LightFace" },
      { character: "r", style: "Lesson_B-hd-LightFace" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Invite students to state the characters, settings, and main events in “Into the Fire.” As a group, create a Story Elements Chart. Then, as a group, construct a summary of “Into the Fire.” If students need more support to summarize the text, use the lesson on page 3 of this guide.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "u", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "m", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "3", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: "", style: "" }
    ]
  },
  {
    styleName: "table_footer",
    content: "Sample Part 1 Story Elements Chart\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "Medium_Condensed" },
      { character: "a", style: "Medium_Condensed" },
      { character: "m", style: "Medium_Condensed" },
      { character: "p", style: "Medium_Condensed" },
      { character: "l", style: "Medium_Condensed" },
      { character: "e", style: "Medium_Condensed" },
      { character: " ", style: "Medium_Condensed" },
      { character: "P", style: "Medium_Condensed" },
      { character: "a", style: "Medium_Condensed" },
      { character: "r", style: "Medium_Condensed" },
      { character: "t", style: "Medium_Condensed" },
      { character: " ", style: "Medium_Condensed" },
      { character: "1", style: "Medium_Condensed" },
      { character: " ", style: "Medium_Condensed" },
      { character: "S", style: "Medium_Condensed" },
      { character: "t", style: "Medium_Condensed" },
      { character: "o", style: "Medium_Condensed" },
      { character: "r", style: "Medium_Condensed" },
      { character: "y", style: "Medium_Condensed" },
      { character: " ", style: "Medium_Condensed" },
      { character: "E", style: "Medium_Condensed" },
      { character: "l", style: "Medium_Condensed" },
      { character: "e", style: "Medium_Condensed" },
      { character: "m", style: "Medium_Condensed" },
      { character: "e", style: "Medium_Condensed" },
      { character: "n", style: "Medium_Condensed" },
      { character: "t", style: "Medium_Condensed" },
      { character: "s", style: "Medium_Condensed" },
      { character: " ", style: "Medium_Condensed" },
      { character: "C", style: "Medium_Condensed" },
      { character: "h", style: "Medium_Condensed" },
      { character: "a", style: "Medium_Condensed" },
      { character: "r", style: "Medium_Condensed" },
      { character: "t", style: "Medium_Condensed" }
    ]
  },
  {
    styleName: "table header",
    content: "Characters",
    parentPageName: "2",
    characterStyles: [
      { character: "C", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" }
    ]
  },
  {
    styleName: "table header",
    content: "Setting",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Sofia, Madeline, other workers at the \nLowell mill",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "FORCED_LINE_BREAK", style: "Character Style 1" },
      { character: "L", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "A textile mill in Lowell, Massachusetts",
    parentPageName: "2",
    characterStyles: [
      { character: "A", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "x", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "L", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" }
    ]
  },
  {
    styleName: "table header",
    content: "Main Events",
    parentPageName: "2",
    characterStyles: [
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "E", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Sofia and Madeline go to work at the textile mill.",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "x", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "A fire breaks out and there is pandemonium.",
    parentPageName: "2",
    characterStyles: [
      { character: "A", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Madeline is caught in her machine and cannot free herself.",
    parentPageName: "2",
    characterStyles: [
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Sofia hears Madeline’s cries for help and goes back to help her.",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Sofia frees Madeline and the girls escape the fire.",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  }
];
 module.exports = paragraphData;
