const paragraphData = [
  {
    styleName: "A-hd",
    content: "Read Chapter 3 and Conclusion RI.6.2, RST.6.2\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "standards" },
      { character: "I", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "2", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "R", style: "standards" },
      { character: "S", style: "standards" },
      { character: "T", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "2", style: "standards" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "If necessary, use the Scaffolded Preview and Cognates for Essential Vocabulary to help students access the text. \r",
    parentPageName: "6",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "V", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Read aloud the supporting question on page 28: How are organisms interconnected in the biosphere?\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: "8", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "w", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "g", style: "Italic" },
      { character: "a", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "m", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "c", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "d", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "n", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "t", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: " ", style: "Italic" },
      { character: "b", style: "Italic" },
      { character: "i", style: "Italic" },
      { character: "o", style: "Italic" },
      { character: "s", style: "Italic" },
      { character: "p", style: "Italic" },
      { character: "h", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "r", style: "Italic" },
      { character: "e", style: "Italic" },
      { character: "?", style: "Italic" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Set a purpose for the first read. \r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "e", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: " ", style: "b" },
      { character: "p", style: "b" },
      { character: "u", style: "b" },
      { character: "r", style: "b" },
      { character: "p", style: "b" },
      { character: "o", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "f", style: "b" },
      { character: "o", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "f", style: "b" },
      { character: "i", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "r", style: "b" },
      { character: "e", style: "b" },
      { character: "a", style: "b" },
      { character: "d", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "teacher-talk bold" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: As you read this chapter, continue using the Double Entry Journal to focus on how organisms are interconnected in the biosphere. Then we’ll collaborate to summarize the main ideas and details.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "[None]" },
      { character: "A", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "D", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "E", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "J", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "SINGLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "z", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Have students create a Double Entry Journal chart on notebook paper, or distribute copies of BLM 1.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "D", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "J", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "B", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "M", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Review the note-taking process as needed.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Choose the reading option that best meets the needs of your students.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "C", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Summarize Key Concepts: Think and Write Independently\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "K", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "B-subhd" },
      { character: "h", style: "B-subhd" },
      { character: "i", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "k", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "a", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "W", style: "B-subhd" },
      { character: "r", style: "B-subhd" },
      { character: "i", style: "B-subhd" },
      { character: "t", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "I", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "p", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: "e", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "t", style: "B-subhd" },
      { character: "l", style: "B-subhd" },
      { character: "y", style: "B-subhd" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Give students a few moments to review their Double Entry Journal and to write their own two- to three-sentence summary of the key information in the chapter. \r",
    parentPageName: "6",
    characterStyles: [
      { character: "G", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "D", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "J", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Use the Sentence Frames to Support Collaborative Conversation for English learners.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "U", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "F", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Bring students together, and ask several volunteers to read their summaries aloud. As a whole group, evaluate the summaries and identify any key information that was omitted. As needed, clarify students’ understanding of the supporting question.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "B", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "SINGLE_RIGHT_QUOTE", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "As a group, construct a written summary of the key ideas in the chapter.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Reread the summary that your class has collaborated to write.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "6",
    characterStyles: [{ character: "", style: "[None]" }],
  },
  {
    styleName: "Label",
    content: "\nSample Summary (Chapter 3/Conclusion)\r",
    parentPageName: "6",
    characterStyles: [
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ")", style: "[None]" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "6",
    characterStyles: [{ character: "", style: "[None]" }],
  },
  {
    styleName: "Sample-body-txt",
    content:
      "Biodiversity is essential because living organisms interact and depend upon one another for survival. Organisms interact in a variety of ways, from symbiosis to predation. Some living organisms develop adaptations to survive. A certain amount of competition for resources is also important in keeping the biosphere healthy and balanced.",
    parentPageName: "6",
    characterStyles: [
      { character: "B", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "O", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
];
module.exports = paragraphData;
