const paragraphData = [teacher-talkteacher-talkteacher-talk
  {
    styleName: "Lesson_B-hd",
    content: "Model Summarizing\r",
    parentPageName: "4",
    characterStyles: [
      { character: "M", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: When we summarize, we include only the most important information in a text. We look for the central ideas. We don’t include all of the details. Let’s summarize a section of this chapter together.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "W", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "m", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "i", style: "i" },
      { character: "z", style: "i" },
      { character: "e", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "l", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "m", style: "i" },
      { character: "o", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "p", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "f", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "x", style: "i" },
      { character: "t", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "W", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "o", style: "i" },
      { character: "k", style: "i" },
      { character: " ", style: "i" },
      { character: "f", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "W", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "l", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "l", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "L", style: "i" },
      { character: "e", style: "i" },
      { character: "t", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "m", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "i", style: "i" },
      { character: "z", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: "c", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: "g", style: "i" },
      { character: "e", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: ".", style: "i" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Reread page 8.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "8", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: This page is about how living things adapt to the climate where they live. I ask myself, “What is the central idea the author wants me to understand about how plants and animals adapt to the climates where they live?”\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "a", style: "i" },
      { character: "g", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "b", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "v", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "v", style: "i" },
      { character: "e", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "I", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "s", style: "i" },
      { character: "k", style: "i" },
      { character: " ", style: "i" },
      { character: "m", style: "i" },
      { character: "y", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: "l", style: "i" },
      { character: "f", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "DOUBLE_LEFT_QUOTE", style: "i" },
      { character: "W", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "u", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "b", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "v", style: "i" },
      { character: "e", style: "i" },
      { character: "?", style: "i" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "i" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Allow responses. Support students to recognize that the author wants readers to understand how animals and plants adapt to certain climates. As part of the explanation, the author defines adaptation and she also describes how a climograph is used to show the pattern of temperature and precipitation in one location.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "A", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: In my summary, I will focus on the central idea. I will not include a definition of adaptation or describe the purpose of a climograph.\r",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "m", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "m", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "y", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "I", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "i", style: "i" },
      { character: "l", style: "i" },
      { character: "l", style: "i" },
      { character: " ", style: "i" },
      { character: "f", style: "i" },
      { character: "o", style: "i" },
      { character: "c", style: "i" },
      { character: "u", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "I", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "i", style: "i" },
      { character: "l", style: "i" },
      { character: "l", style: "i" },
      { character: " ", style: "i" },
      { character: "n", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "f", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "c", style: "i" },
      { character: "r", style: "i" },
      { character: "i", style: "i" },
      { character: "b", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "u", style: "i" },
      { character: "r", style: "i" },
      { character: "p", style: "i" },
      { character: "o", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "o", style: "i" },
      { character: "g", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "h", style: "i" },
      { character: ".", style: "i" },
      { character: "", style: "[None]" }
    ]
  },
  {
    styleName: "table_footer",
    content: "Sample Summary (Chapter 1)",
    parentPageName: "4",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "a", style: "b" },
      { character: "m", style: "b" },
      { character: "p", style: "b" },
      { character: "l", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "S", style: "b" },
      { character: "u", style: "b" },
      { character: "m", style: "b" },
      { character: "m", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "y", style: "b" },
      { character: " ", style: "b" },
      { character: "(", style: "b" },
      { character: "C", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "p", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "1", style: "b" },
      { character: ")", style: "b" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Climate affects animal and plant adaptations. In hot climates, some animals stay cool by burrowing underground during the hot day and feeding at night. Plants have adaptations for the heat, too, such as leaf coatings that keep them cool. Organisms also adapt to precipitation. In places with lots of rain, for example, plants have a leaf adaptation in which they release much of the water the roots have absorbed back into the atmosphere. Meanwhile, plants in dry climates store water or have very long roots to reach underground water.",
    parentPageName: "4",
    characterStyles: [
      { character: "C", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "I", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "P", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "O", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "I", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "x", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "M", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  }
];
 module.exports = paragraphData;
