const paragraphData = [
  {
    styleName: "Lesson_A-hd",
    content:
      "Close Reading Option 3: Identify an Author’s Claim and Supporting Evidence RI.6.8, RST.6-6.1\r",
    parentPageName: "9",
    characterStyles: [
      { character: "C", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "O", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "SINGLE_RIGHT_QUOTE", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "8", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: "-", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "1", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_B-hd",
    content: "Model Finding Text Evidence\r",
    parentPageName: "9",
    characterStyles: [
      { character: "M", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "F", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Display and read aloud the close reading question.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "D", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Explain that the question asks the reader to find evidence in the text that supports the author’s claim.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "E", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "SINGLE_RIGHT_QUOTE", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content:
      "Say: I’m going to show you how I read closely to evaluate an author’s argument or claim. To evaluate the validity of an author’s claim, I need to identify evidence in the text that supports it.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "i" },
      { character: "I", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "g", style: "i" },
      { character: "o", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "I", style: "i" },
      { character: " ", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: "l", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "v", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "g", style: "i" },
      { character: "u", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "T", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "v", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "v", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "I", style: "i" },
      { character: " ", style: "i" },
      { character: "n", style: "i" },
      { character: "e", style: "i" },
      { character: "e", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "f", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "v", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "x", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "p", style: "i" },
      { character: "p", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: ".", style: "i" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Reread page 10 while students follow along.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "0", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content:
      "Say: The author provides evidence to support the claim that photosynthesis is the basis of all life in the ocean. She explains that the energy obtained from photosynthesis allows plants and green algae to grow. She also states that photosynthesis produces oxygen that is used by water animals.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "i" },
      { character: "T", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "r", style: "i" },
      { character: "o", style: "i" },
      { character: "v", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "v", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "p", style: "i" },
      { character: "p", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "S", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "x", style: "i" },
      { character: "p", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "g", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "b", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "e", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "f", style: "i" },
      { character: "r", style: "i" },
      { character: "o", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: "s", style: "i" },
      { character: "y", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "g", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "g", style: "i" },
      { character: "a", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "g", style: "i" },
      { character: "r", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "S", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "s", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: "s", style: "i" },
      { character: "y", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "r", style: "i" },
      { character: "o", style: "i" },
      { character: "d", style: "i" },
      { character: "u", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "x", style: "i" },
      { character: "y", style: "i" },
      { character: "g", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "u", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "b", style: "i" },
      { character: "y", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Display a blank graphic organizer like the one in the margin. Write the argument or claim in the left column, and then ask students to recall evidence in the text that directly supports the argument.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "D", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "W", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Complete the graphic organizer.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_B-hd",
    content: "Support Practice\r",
    parentPageName: "9",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Read aloud page 13 as students follow along. Display a blank graphic organizer like the sample in the margin.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "1", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "D", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content:
      "Collaborative conversation(turn and talk). Say: Think about the author’s claim that there is a tremendous amount of life in the twilight zone. Find evidence in the text to support that argument. Talk to your partner, and complete a graphic organizer.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "C", style: "b" },
      { character: "o", style: "b" },
      { character: "l", style: "b" },
      { character: "l", style: "b" },
      { character: "a", style: "b" },
      { character: "b", style: "b" },
      { character: "o", style: "b" },
      { character: "r", style: "b" },
      { character: "a", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "c", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: "a", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: "(", style: "b" },
      { character: "t", style: "b" },
      { character: "u", style: "b" },
      { character: "r", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "a", style: "b" },
      { character: "l", style: "b" },
      { character: "k", style: "b" },
      { character: ")", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "b" },
      { character: "S", style: "i" },
      { character: "a", style: "i" },
      { character: "y", style: "i" },
      { character: ":", style: "i" },
      { character: " ", style: "i" },
      { character: "T", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "k", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "b", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "m", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "f", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "w", style: "i" },
      { character: "i", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "g", style: "i" },
      { character: "h", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "z", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "e", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "F", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "v", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "x", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "p", style: "i" },
      { character: "p", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "g", style: "i" },
      { character: "u", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "t", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "T", style: "i" },
      { character: "a", style: "i" },
      { character: "l", style: "i" },
      { character: "k", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: "n", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: ",", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "o", style: "i" },
      { character: "m", style: "i" },
      { character: "p", style: "i" },
      { character: "l", style: "i" },
      { character: "e", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "g", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "h", style: "i" },
      { character: "i", style: "i" },
      { character: "c", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "g", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "i", style: "i" },
      { character: "z", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: ".", style: "i" },
    ],
  },
  {
    styleName: "Lesson_B-hd",
    content: "Find Text Evidence Independently\r",
    parentPageName: "9",
    characterStyles: [
      { character: "F", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "y", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Body-txt",
    content:
      "Ask students to reread page 38. Have them find evidence to support the author’s claim that when people destroy a habitat, they also destroy all the plants and animals in it.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: "8", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "H", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "SINGLE_RIGHT_QUOTE", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
    ],
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content:
      "Ask: How did supporting the author’s claim with evidence from the text help your understanding of the concepts?",
    parentPageName: "9",
    characterStyles: [
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "i" },
      { character: "H", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "p", style: "i" },
      { character: "p", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "u", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "l", style: "i" },
      { character: "a", style: "i" },
      { character: "i", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "v", style: "i" },
      { character: "i", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "f", style: "i" },
      { character: "r", style: "i" },
      { character: "o", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "x", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "l", style: "i" },
      { character: "p", style: "i" },
      { character: " ", style: "i" },
      { character: "y", style: "i" },
      { character: "o", style: "i" },
      { character: "u", style: "i" },
      { character: "r", style: "i" },
      { character: " ", style: "i" },
      { character: "u", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "p", style: "i" },
      { character: "t", style: "i" },
      { character: "s", style: "i" },
      { character: "?", style: "i" },
    ],
  },
  {
    styleName: "Lesson_Table-body-txt",
    content:
      "What evidence supports the author’s claim that photosynthesis is the basis of all life in the ocean?",
    parentPageName: "9",
    characterStyles: [
      { character: "W", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "?", style: "Character Style 1" },
    ],
  },
];
module.exports = paragraphData;
