const paragraphData = [bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  {
    styleName: "Chart-body-txt",
    content: "",
    parentPageName: "6",
    characterStyles: [
      { character: "", style: "b" }
    ]
  },
  {
    styleName: "Chart-hd",
    content: "Support for English Learners",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" }
    ]
  },
  {
    styleName: "Chart-subhd",
    content: "Scaffolded Preview \nChapter 3\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "C", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "p", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "3", style: "b" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Pages 32–34. The ocean is home to many different organisms. What are these animals? \r",
    parentPageName: "6",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "3", style: "b" },
      { character: "2", style: "b" },
      { character: "EN_DASH", style: "b" },
      { character: "3", style: "b" },
      { character: "4", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "b" },
      { character: "T", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "g", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "W", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" },
      { character: " ", style: "[None]" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Page 35. Look at the coral reef. It offers food and shelter for many organisms.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "3", style: "b" },
      { character: "5", style: "b" },
      { character: ".", style: "[None]" },
      { character: " ", style: "Sidebar-tt" },
      { character: "L", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "I", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "f", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "g", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Page 36. Look at these deep sea creatures. How do they survive so deep down?\r",
    parentPageName: "6",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "3", style: "b" },
      { character: "6", style: "b" },
      { character: ".", style: "[None]" },
      { character: " ", style: "Sidebar-tt" },
      { character: "L", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "k", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "H", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "w", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "?", style: "Sidebar-tt" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Conclusion\r",
    parentPageName: "6",
    characterStyles: [
      { character: "C", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "l", style: "b" },
      { character: "u", style: "b" },
      { character: "s", style: "b" },
      { character: "i", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" }
    ]
  },
  {
    styleName: "Chart-body-txt",
    content: "Pages 42–43. Over the last century, scientists have learned a lot about the ocean, but the vast and deep sea still holds mysteries to be explored.",
    parentPageName: "6",
    characterStyles: [
      { character: "P", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "4", style: "b" },
      { character: "2", style: "b" },
      { character: "EN_DASH", style: "b" },
      { character: "4", style: "b" },
      { character: "3", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "Sidebar-tt" },
      { character: "O", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: ",", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "c", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: ",", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "u", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "v", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: "n", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "a", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "h", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "m", style: "Sidebar-tt" },
      { character: "y", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "i", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "s", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "t", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "b", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: " ", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "x", style: "Sidebar-tt" },
      { character: "p", style: "Sidebar-tt" },
      { character: "l", style: "Sidebar-tt" },
      { character: "o", style: "Sidebar-tt" },
      { character: "r", style: "Sidebar-tt" },
      { character: "e", style: "Sidebar-tt" },
      { character: "d", style: "Sidebar-tt" },
      { character: ".", style: "Sidebar-tt" }
    ]
  },
  {
    styleName: "Chart-subhd",
    content: "Cognates (English/Spanish)\nfor Essential Vocabulary\r",
    parentPageName: "6",
    characterStyles: [
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: ")", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "V", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "nekton/el necton (p. 33)\r",
    parentPageName: "6",
    characterStyles: [
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: ")", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "plankton/el plancton (p. 33)",
    parentPageName: "6",
    characterStyles: [
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "/", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "(", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: ")", style: "[None]" }
    ]
  },
  {
    styleName: "Chart-subhd",
    content: "Sentence Frames to Support Collaborative Conversation\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "F", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "C", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "Based on my notes, the chapter’s central idea is _____.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "B", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: "s", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: "d", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "o", style: "Chart-list-italic" },
      { character: "n", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "m", style: "Chart-list-italic" },
      { character: "y", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "n", style: "Chart-list-italic" },
      { character: "o", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: "s", style: "Chart-list-italic" },
      { character: ",", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: "h", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "c", style: "Chart-list-italic" },
      { character: "h", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: "p", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: "r", style: "Chart-list-italic" },
      { character: "SINGLE_RIGHT_QUOTE", style: "Chart-list-italic" },
      { character: "s", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "c", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: "n", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: "r", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: "l", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "i", style: "Chart-list-italic" },
      { character: "d", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "i", style: "Chart-list-italic" },
      { character: "s", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: ".", style: "Chart-list-italic" }
    ]
  },
  {
    styleName: "Sidebar-body-txt",
    content: "Some factors that affect sea life include _____.",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "Chart-list-italic" },
      { character: "o", style: "Chart-list-italic" },
      { character: "m", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "f", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: "c", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: "o", style: "Chart-list-italic" },
      { character: "r", style: "Chart-list-italic" },
      { character: "s", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: "h", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: "f", style: "Chart-list-italic" },
      { character: "f", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: "c", style: "Chart-list-italic" },
      { character: "t", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "s", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: "a", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "l", style: "Chart-list-italic" },
      { character: "i", style: "Chart-list-italic" },
      { character: "f", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "i", style: "Chart-list-italic" },
      { character: "n", style: "Chart-list-italic" },
      { character: "c", style: "Chart-list-italic" },
      { character: "l", style: "Chart-list-italic" },
      { character: "u", style: "Chart-list-italic" },
      { character: "d", style: "Chart-list-italic" },
      { character: "e", style: "Chart-list-italic" },
      { character: " ", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: "_", style: "Chart-list-italic" },
      { character: ".", style: "Chart-list-italic" }
    ]
  }
];
 module.exports = paragraphData;
