const paragraphData = [teacher-talk
  {
    styleName: "Lesson_A-hd",
    content: "Read Varuna Takes a Job with the Census \nRL.6.2 \r",
    parentPageName: "2",
    characterStyles: [
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "V", style: "b-ital" },
      { character: "a", style: "b-ital" },
      { character: "r", style: "b-ital" },
      { character: "u", style: "b-ital" },
      { character: "n", style: "b-ital" },
      { character: "a", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "T", style: "b-ital" },
      { character: "a", style: "b-ital" },
      { character: "k", style: "b-ital" },
      { character: "e", style: "b-ital" },
      { character: "s", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "a", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "J", style: "b-ital" },
      { character: "o", style: "b-ital" },
      { character: "b", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "w", style: "b-ital" },
      { character: "i", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: "h", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "t", style: "b-ital" },
      { character: "h", style: "b-ital" },
      { character: "e", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "C", style: "b-ital" },
      { character: "e", style: "b-ital" },
      { character: "n", style: "b-ital" },
      { character: "s", style: "b-ital" },
      { character: "u", style: "b-ital" },
      { character: "s", style: "b-ital" },
      { character: " ", style: "b-ital" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "6", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: " ", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_A-hd",
    content: "Preview Book\r",
    parentPageName: "2",
    characterStyles: [
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "B", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "k", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Invite students to read the story titles and study the illustrations on the cover. Invite a volunteer to read aloud the book description on the back cover. Review that stories of the same genre share certain characteristics, or features. Ask students to turn to pages 2–3, and invite volunteers to read the questions and answers about science fiction. Then read and discuss the “Features of Science Fiction” web. Ask students to turn to pages 5–7. Explain that two different scientific stories are in this book. Together, read about the kinds of science fiction stories. \r",
    parentPageName: "2",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "2", style: "[None]" },
      { character: "EN_DASH", style: "[None]" },
      { character: "3", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "q", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "DOUBLE_LEFT_QUOTE", style: "[None]" },
      { character: "F", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "F", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "5", style: "[None]" },
      { character: "EN_DASH", style: "[None]" },
      { character: "7", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "If your students need more support, use the Scaffolded Preview provided. \r",
    parentPageName: "2",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_A-hd",
    content: "Set a Purpose\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: We know that science fiction includes key story elements, such as characters and a problem to solve. As you read Varuna Takes a Job with the Census, use self-stick notes to identify the characters and setting and to flag the main events.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "a", style: "b" },
      { character: "y", style: "b" },
      { character: ":", style: "b" },
      { character: " ", style: "b" },
      { character: "W", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "k", style: "b" },
      { character: "n", style: "b" },
      { character: "o", style: "b" },
      { character: "w", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "c", style: "b" },
      { character: "i", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "f", style: "b" },
      { character: "i", style: "b" },
      { character: "c", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "l", style: "b" },
      { character: "u", style: "b" },
      { character: "d", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "k", style: "b" },
      { character: "e", style: "b" },
      { character: "y", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "t", style: "b" },
      { character: "o", style: "b" },
      { character: "r", style: "b" },
      { character: "y", style: "b" },
      { character: " ", style: "b" },
      { character: "e", style: "b" },
      { character: "l", style: "b" },
      { character: "e", style: "b" },
      { character: "m", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "t", style: "b" },
      { character: "s", style: "b" },
      { character: ",", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "u", style: "b" },
      { character: "c", style: "b" },
      { character: "h", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "c", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "a", style: "b" },
      { character: "c", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: " ", style: "b" },
      { character: "p", style: "b" },
      { character: "r", style: "b" },
      { character: "o", style: "b" },
      { character: "b", style: "b" },
      { character: "l", style: "b" },
      { character: "e", style: "b" },
      { character: "m", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "o", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "o", style: "b" },
      { character: "l", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "b" },
      { character: "A", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "y", style: "b" },
      { character: "o", style: "b" },
      { character: "u", style: "b" },
      { character: " ", style: "b" },
      { character: "r", style: "b" },
      { character: "e", style: "b" },
      { character: "a", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "V", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "u", style: "b" },
      { character: "n", style: "b" },
      { character: "a", style: "b" },
      { character: " ", style: "b" },
      { character: "T", style: "b" },
      { character: "a", style: "b" },
      { character: "k", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: " ", style: "b" },
      { character: "J", style: "b" },
      { character: "o", style: "b" },
      { character: "b", style: "b" },
      { character: " ", style: "b" },
      { character: "w", style: "b" },
      { character: "i", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "C", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "s", style: "b" },
      { character: "u", style: "b" },
      { character: "s", style: "b" },
      { character: ",", style: "b" },
      { character: " ", style: "b" },
      { character: "u", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: "l", style: "b" },
      { character: "f", style: "b" },
      { character: "-", style: "b" },
      { character: "s", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "c", style: "b" },
      { character: "k", style: "b" },
      { character: " ", style: "b" },
      { character: "n", style: "b" },
      { character: "o", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "o", style: "b" },
      { character: " ", style: "b" },
      { character: "i", style: "b" },
      { character: "d", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "f", style: "b" },
      { character: "y", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "c", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "a", style: "b" },
      { character: "c", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: "t", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: "g", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "o", style: "b" },
      { character: " ", style: "b" },
      { character: "f", style: "b" },
      { character: "l", style: "b" },
      { character: "a", style: "b" },
      { character: "g", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "m", style: "b" },
      { character: "a", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "e", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "t", style: "b" },
      { character: "s", style: "b" },
      { character: ".", style: "b" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Choose the reading option that best meets your students’ needs.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "C", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "SINGLE_RIGHT_QUOTE", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Summarize Key Story Elements: Think and Write Together\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "z", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "K", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ":", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "k", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "W", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Invite students to state the story elements in Varuna Takes a Job with the Census. As a group, create a Key Story Elements chart. Then, as a group, construct a summary of the story. If students need more support, use the lesson. \r",
    parentPageName: "2",
    characterStyles: [
      { character: "I", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "V", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "u", style: "i" },
      { character: "n", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "T", style: "i" },
      { character: "a", style: "i" },
      { character: "k", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: " ", style: "i" },
      { character: "J", style: "i" },
      { character: "o", style: "i" },
      { character: "b", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "i", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "C", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "s", style: "i" },
      { character: "u", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "A", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "K", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "T", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "I", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: ".", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "", style: "[None]" }
    ]
  },
  {
    styleName: "table_label",
    content: "Sample Key Story Elements Chart ",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "labels" },
      { character: "a", style: "labels" },
      { character: "m", style: "labels" },
      { character: "p", style: "labels" },
      { character: "l", style: "labels" },
      { character: "e", style: "labels" },
      { character: " ", style: "labels" },
      { character: "K", style: "labels" },
      { character: "e", style: "labels" },
      { character: "y", style: "labels" },
      { character: " ", style: "labels" },
      { character: "S", style: "labels" },
      { character: "t", style: "labels" },
      { character: "o", style: "labels" },
      { character: "r", style: "labels" },
      { character: "y", style: "labels" },
      { character: " ", style: "labels" },
      { character: "E", style: "labels" },
      { character: "l", style: "labels" },
      { character: "e", style: "labels" },
      { character: "m", style: "labels" },
      { character: "e", style: "labels" },
      { character: "n", style: "labels" },
      { character: "t", style: "labels" },
      { character: "s", style: "labels" },
      { character: " ", style: "labels" },
      { character: "C", style: "labels" },
      { character: "h", style: "labels" },
      { character: "a", style: "labels" },
      { character: "r", style: "labels" },
      { character: "t", style: "labels" },
      { character: " ", style: "labels" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Characters",
    parentPageName: "2",
    characterStyles: [
      { character: "C", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "r", style: "b" },
      { character: "a", style: "b" },
      { character: "c", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Setting",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "b" },
      { character: "e", style: "b" },
      { character: "t", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: "g", style: "b" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Varuna, Gphimpy, planet Earth",
    parentPageName: "2",
    characterStyles: [
      { character: "V", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "G", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "E", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Seraphim galaxy; Universe Central",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "x", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: ";", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "U", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "C", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "Main Events\r",
    parentPageName: "2",
    characterStyles: [
      { character: "M", style: "b" },
      { character: "a", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "E", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "t", style: "b" },
      { character: "s", style: "b" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Varuna starts a job with Universe Central, working for the census. \r",
    parentPageName: "2",
    characterStyles: [
      { character: "V", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "j", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "U", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "C", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Varuna meets her boss Gphimpy, who tells her that she must count every sentient being.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "V", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "G", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Varuna discovers new races of sentient beings.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "V", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Varuna interviews planet Earth, whose beings became extinct.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "V", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "E", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "x", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" }
    ]
  },
  {
    styleName: "Chart-body-txt-bullets",
    content: "Varuna leaves her toy Onglantichi behind while working, but her boss returns it to her and tells her that she did a great job on her first day. ",
    parentPageName: "2",
    characterStyles: [
      { character: "V", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "O", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "k", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: ",", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "j", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "b", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: ".", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" }
    ]
  }
];
 module.exports = paragraphData;
