const paragraphData = [b
  {
    styleName: "Generic_sidebar_A-hd",
    content: "Scaffolded Preview for \nELs and Struggling Readers\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "P", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "w", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "f", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "FORCED_LINE_BREAK", style: "[None]" },
      { character: "E", style: "[None]" },
      { character: "L", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "S", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "R", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "s", style: "[None]" }
    ]
  },
  {
    styleName: "Generic_sidebar_Body-txt",
    content: "Support students to access the text by orally introducing academic vocabulary, language structures, and concepts.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "S", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "h", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "x", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "m", style: "[None]" },
      { character: "i", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "v", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "b", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "y", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "l", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "g", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "u", style: "[None]" },
      { character: "r", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ",", style: "[None]" },
      { character: " ", style: "[None]" },
      { character: "a", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "d", style: "[None]" },
      { character: "NONBREAKING_SPACE", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "o", style: "[None]" },
      { character: "n", style: "[None]" },
      { character: "c", style: "[None]" },
      { character: "e", style: "[None]" },
      { character: "p", style: "[None]" },
      { character: "t", style: "[None]" },
      { character: "s", style: "[None]" },
      { character: ".", style: "[None]" }
    ]
  },
  {
    styleName: "Generic_sidebar_Body-txt",
    content: "Pages 2–3. Notice the blue bfaced words on these pages. Some are Spanish words and some are English words. Both types are defined at the bottom of each page.\r",
    parentPageName: "2",
    characterStyles: [
      { character: "P", style: "Medium_Condensed" },
      { character: "a", style: "Medium_Condensed" },
      { character: "g", style: "Medium_Condensed" },
      { character: "e", style: "Medium_Condensed" },
      { character: "s", style: "Medium_Condensed" },
      { character: " ", style: "Medium_Condensed" },
      { character: "2", style: "Medium_Condensed" },
      { character: "EN_DASH", style: "Medium_Condensed" },
      { character: "3", style: "Medium_Condensed" },
      { character: ".", style: "Medium_Condensed" },
      { character: " ", style: "[None]" },
      { character: "N", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "b", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "b", style: "i" },
      { character: "o", style: "i" },
      { character: "l", style: "i" },
      { character: "d", style: "i" },
      { character: "f", style: "i" },
      { character: "a", style: "i" },
      { character: "c", style: "i" },
      { character: "e", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "d", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "a", style: "i" },
      { character: "g", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "S", style: "i" },
      { character: "o", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "S", style: "i" },
      { character: "p", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: "h", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "d", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "n", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "s", style: "i" },
      { character: "o", style: "i" },
      { character: "m", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "E", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: "l", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: "h", style: "i" },
      { character: " ", style: "i" },
      { character: "w", style: "i" },
      { character: "o", style: "i" },
      { character: "r", style: "i" },
      { character: "d", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "B", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "y", style: "i" },
      { character: "p", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "d", style: "i" },
      { character: "e", style: "i" },
      { character: "f", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "e", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "b", style: "i" },
      { character: "o", style: "i" },
      { character: "t", style: "i" },
      { character: "t", style: "i" },
      { character: "o", style: "i" },
      { character: "m", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "f", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "a", style: "i" },
      { character: "c", style: "i" },
      { character: "h", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "a", style: "i" },
      { character: "g", style: "i" },
      { character: "e", style: "i" },
      { character: ".", style: "i" }
    ]
  },
  {
    styleName: "Generic_sidebar_Body-txt",
    content: "Pages 4–5. Now look at the illustration on these pages. What is happening here based on the characters’ expressions?",
    parentPageName: "2",
    characterStyles: [
      { character: "P", style: "Medium_Condensed" },
      { character: "a", style: "Medium_Condensed" },
      { character: "g", style: "Medium_Condensed" },
      { character: "e", style: "Medium_Condensed" },
      { character: "s", style: "Medium_Condensed" },
      { character: " ", style: "Medium_Condensed" },
      { character: "4", style: "Medium_Condensed" },
      { character: "EN_DASH", style: "Medium_Condensed" },
      { character: "5", style: "Medium_Condensed" },
      { character: ".", style: "Medium_Condensed" },
      { character: " ", style: "[None]" },
      { character: "N", style: "i" },
      { character: "o", style: "i" },
      { character: "w", style: "i" },
      { character: " ", style: "i" },
      { character: "l", style: "i" },
      { character: "o", style: "i" },
      { character: "o", style: "i" },
      { character: "k", style: "i" },
      { character: " ", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "l", style: "i" },
      { character: "l", style: "i" },
      { character: "u", style: "i" },
      { character: "s", style: "i" },
      { character: "t", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "p", style: "i" },
      { character: "a", style: "i" },
      { character: "g", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: ".", style: "i" },
      { character: " ", style: "i" },
      { character: "W", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "t", style: "i" },
      { character: " ", style: "i" },
      { character: "i", style: "i" },
      { character: "s", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "p", style: "i" },
      { character: "p", style: "i" },
      { character: "e", style: "i" },
      { character: "n", style: "i" },
      { character: "i", style: "i" },
      { character: "n", style: "i" },
      { character: "g", style: "i" },
      { character: " ", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "b", style: "i" },
      { character: "a", style: "i" },
      { character: "s", style: "i" },
      { character: "e", style: "i" },
      { character: "d", style: "i" },
      { character: " ", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: " ", style: "i" },
      { character: "t", style: "i" },
      { character: "h", style: "i" },
      { character: "e", style: "i" },
      { character: " ", style: "i" },
      { character: "c", style: "i" },
      { character: "h", style: "i" },
      { character: "a", style: "i" },
      { character: "r", style: "i" },
      { character: "a", style: "i" },
      { character: "c", style: "i" },
      { character: "t", style: "i" },
      { character: "e", style: "i" },
      { character: "r", style: "i" },
      { character: "s", style: "i" },
      { character: "SINGLE_RIGHT_QUOTE", style: "i" },
      { character: " ", style: "i" },
      { character: "e", style: "i" },
      { character: "x", style: "i" },
      { character: "p", style: "i" },
      { character: "r", style: "i" },
      { character: "e", style: "i" },
      { character: "s", style: "i" },
      { character: "s", style: "i" },
      { character: "i", style: "i" },
      { character: "o", style: "i" },
      { character: "n", style: "i" },
      { character: "s", style: "i" },
      { character: "?", style: "i" }
    ]
  }
];
 module.exports = paragraphData;
