const paragraphData = [
  {
    styleName: "A-hd",
    content:
      "Close Reading Option 3: Draw and Support Inferences Using Text Evidence RI.6.1, RST.6.1\r",
    parentPageName: "9",
    characterStyles: [
      { character: "C", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "3", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "A-subhd" },
      { character: "r", style: "A-subhd" },
      { character: "a", style: "A-subhd" },
      { character: "w", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "a", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "d", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "S", style: "A-subhd" },
      { character: "u", style: "A-subhd" },
      { character: "p", style: "A-subhd" },
      { character: "p", style: "A-subhd" },
      { character: "o", style: "A-subhd" },
      { character: "r", style: "A-subhd" },
      { character: "t", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "I", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "f", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "r", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "c", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "s", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "U", style: "A-subhd" },
      { character: "s", style: "A-subhd" },
      { character: "i", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "g", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "T", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "x", style: "A-subhd" },
      { character: "t", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "E", style: "A-subhd" },
      { character: "v", style: "A-subhd" },
      { character: "i", style: "A-subhd" },
      { character: "d", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: "n", style: "A-subhd" },
      { character: "c", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "R", style: "standards" },
      { character: "I", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "1", style: "standards" },
      { character: ",", style: "standards" },
      { character: " ", style: "standards" },
      { character: "R", style: "standards" },
      { character: "S", style: "standards" },
      { character: "T", style: "standards" },
      { character: ".", style: "standards" },
      { character: "6", style: "standards" },
      { character: ".", style: "standards" },
      { character: "1", style: "standards" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "For students with a solid grasp of the content, accelerate their access to on-level complex text by having them read select passages of the PRIME On-Level edition.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "F", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "-", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "R", style: "" },
      { character: "I", style: "" },
      { character: "M", style: "" },
      { character: "E", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "n", style: "" },
      { character: "-", style: "" },
      { character: "L", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Model Finding Text Evidence \r",
    parentPageName: "9",
    characterStyles: [
      { character: "M", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Display and read aloud the close reading question.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "9",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Explain that the question asks the reader to make an inference based on evidence in the text.   \r",
    parentPageName: "9",
    characterStyles: [
      { character: "E", style: "b" },
      { character: "x", style: "b" },
      { character: "p", style: "b" },
      { character: "l", style: "b" },
      { character: "a", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "a", style: "b" },
      { character: "t", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "q", style: "b" },
      { character: "u", style: "b" },
      { character: "e", style: "b" },
      { character: "s", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "s", style: "b" },
      { character: "k", style: "b" },
      { character: "s", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "r", style: "b" },
      { character: "e", style: "b" },
      { character: "a", style: "b" },
      { character: "d", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "o", style: "b" },
      { character: " ", style: "b" },
      { character: "m", style: "b" },
      { character: "a", style: "b" },
      { character: "k", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: "f", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "b", style: "b" },
      { character: "a", style: "b" },
      { character: "s", style: "b" },
      { character: "e", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "e", style: "b" },
      { character: "v", style: "b" },
      { character: "i", style: "b" },
      { character: "d", style: "b" },
      { character: "e", style: "b" },
      { character: "n", style: "b" },
      { character: "c", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "i", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "h", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "e", style: "b" },
      { character: "x", style: "b" },
      { character: "t", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "b" },
      { character: " ", style: "b" },
      { character: " ", style: "b" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: I’m going to show you how I make inferences when I read. When we infer, we use information from the text to form an understanding that is not directly stated in the text. To make an inference, I read the text closely and think about what is understood, but not necessarily stated. There must be evidence in the text to support my inference.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "I", style: "teacher-talk" },
      { character: "SINGLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "W", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Reread page 26 while students follow along.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "6", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: We read that the extinction of dinosaurs freed up the niches they had occupied. Although the author doesn’t state it directly, I can infer that if niches were “freed up” after the extinction of the dinosaurs, then the dinosaurs had been the dominant species in their habitat.  \r",
    parentPageName: "9",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "W", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "A", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "SINGLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "DOUBLE_LEFT_QUOTE", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Display a blank graphic organizer like the one in the margin. Write in the inference and then ask students to recall the text evidence that directly supports the inference.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Complete the graphic organizer. \r",
    parentPageName: "9",
    characterStyles: [
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Ask: What other inferences can you draw from the text and support using text evidence?\r",
    parentPageName: "9",
    characterStyles: [
      { character: "A", style: "teacher-talk bold" },
      { character: "s", style: "teacher-talk bold" },
      { character: "k", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "W", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "?", style: "teacher-talk" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Support Practice\r",
    parentPageName: "9",
    characterStyles: [
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Read aloud the third paragraph on page 36 as students follow along. Display a blank graphic organizer like the sample in the margin. \r",
    parentPageName: "9",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "3", style: "" },
      { character: "6", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Collaborative conversation (turn and talk). Say: Think about the facts you read in the text. Use the evidence in the text to make an inference. What inference can you make from the evidence? Talk to your partner, and complete a graphic organizer.\r",
    parentPageName: "9",
    characterStyles: [
      { character: "C", style: "b" },
      { character: "o", style: "b" },
      { character: "l", style: "b" },
      { character: "l", style: "b" },
      { character: "a", style: "b" },
      { character: "b", style: "b" },
      { character: "o", style: "b" },
      { character: "r", style: "b" },
      { character: "a", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: " ", style: "b" },
      { character: "c", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: "v", style: "b" },
      { character: "e", style: "b" },
      { character: "r", style: "b" },
      { character: "s", style: "b" },
      { character: "a", style: "b" },
      { character: "t", style: "b" },
      { character: "i", style: "b" },
      { character: "o", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "(", style: "b" },
      { character: "t", style: "b" },
      { character: "u", style: "b" },
      { character: "r", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "a", style: "b" },
      { character: "l", style: "b" },
      { character: "k", style: "b" },
      { character: ")", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "" },
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "U", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "W", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "?", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "z", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Find Text Evidence Independently\r",
    parentPageName: "9",
    characterStyles: [
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Ask students to reread the “Future of Biodiversity” section on page 38. Have them use evidence from the text to make an inference about why biodiversity is essential to the future of our planet. \r",
    parentPageName: "9",
    characterStyles: [
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "F", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "y", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "3", style: "" },
      { character: "8", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "H", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Ask: How did making inferences as you read help your understanding of \nthe concepts?\r",
    parentPageName: "9",
    characterStyles: [
      { character: "A", style: "teacher-talk bold" },
      { character: "s", style: "teacher-talk bold" },
      { character: "k", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "H", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "FORCED_LINE_BREAK", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "?", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "9",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "The extinction of dinosaurs freed up the niches they had occupied. What inference can the reader make based on this information from the text?",
    parentPageName: "9",
    characterStyles: [
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "c", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: "?", style: "" },
    ],
  },
];
module.exports = paragraphData;
