const paragraphData = [teacher-talkteacher-talk
  {
    styleName: "Lesson_A-hd",
    content: "Close Reading Option 1: Identify and Analyze Theme \nRL.6.1, RL.6.2, RL.6.3, W.6.10, SL.6.1\r",
    parentPageName: "6",
    characterStyles: [
      { character: "C", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: "z", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "R", style: "" },
      { character: "L", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "1", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "L", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "2", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "L", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "3", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "1", style: "" },
      { character: "0", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "L", style: "" },
      { character: ".", style: "" },
      { character: "6", style: "" },
      { character: ".", style: "" },
      { character: "1", style: "" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Model Finding Text Evidence\r",
    parentPageName: "6",
    characterStyles: [
      { character: "M", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Display and read aloud the close reading question.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ".", style: "" },
      { character: "", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Remind students that the theme of a story is a central message. Explain that this question asks readers to identify a theme in the play and then locate text evidence that illustrates it.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "x", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: Finding the theme of a story requires readers to make an inference based on text evidence. We need to look at the characters’ actions and how they affect the plot of \nthe story.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Reread pages 10–11.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "1", style: "" },
      { character: "0", style: "" },
      { character: "EN_DASH", style: "" },
      { character: "1", style: "" },
      { character: "1", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Tchr-tlk",
    content: "Say: In the courtroom scene, I notice that Mr. Brownlow shows kindness towards Oliver. When the judge sentences Oliver to three months of hard labor, Mr. Brownlow says, “I’ve decided that I’m not pressing any charges. This boy is very ill.” Mr. Brownlow takes Oliver home and takes care of him. This act of kindness dramatically changes the course of Oliver’s life in a positive way. Instead of going to prison, he has a home where he is cared for. I think a central theme of the play is the importance of showing kindness to others.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "n", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "W", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "j", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "n", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "I", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "n", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "k", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Display a blank Text Evidence Chart and model how you record the text evidence you found.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "y", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Support Practice\r",
    parentPageName: "6",
    characterStyles: [
      { character: "S", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "P", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Ask students to turn to page 27.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "7", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Collaborative conversation (turn and talk). Ask students to turn to a partner, reread pages 27–28, and find additional text evidence that supports the theme of the importance of showing kindness. Remind students to stay on topic, build on each other’s ideas, and ask questions to clarify each other’s thoughts.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "C", style: "Med_cond" },
      { character: "o", style: "Med_cond" },
      { character: "l", style: "Med_cond" },
      { character: "l", style: "Med_cond" },
      { character: "a", style: "Med_cond" },
      { character: "b", style: "Med_cond" },
      { character: "o", style: "Med_cond" },
      { character: "r", style: "Med_cond" },
      { character: "a", style: "Med_cond" },
      { character: "t", style: "Med_cond" },
      { character: "i", style: "Med_cond" },
      { character: "v", style: "Med_cond" },
      { character: "e", style: "Med_cond" },
      { character: " ", style: "Med_cond" },
      { character: "c", style: "Med_cond" },
      { character: "o", style: "Med_cond" },
      { character: "n", style: "Med_cond" },
      { character: "v", style: "Med_cond" },
      { character: "e", style: "Med_cond" },
      { character: "r", style: "Med_cond" },
      { character: "s", style: "Med_cond" },
      { character: "a", style: "Med_cond" },
      { character: "t", style: "Med_cond" },
      { character: "i", style: "Med_cond" },
      { character: "o", style: "Med_cond" },
      { character: "n", style: "Med_cond" },
      { character: " ", style: "Med_cond" },
      { character: "(", style: "Med_cond" },
      { character: "t", style: "Med_cond" },
      { character: "u", style: "Med_cond" },
      { character: "r", style: "Med_cond" },
      { character: "n", style: "Med_cond" },
      { character: " ", style: "Med_cond" },
      { character: "a", style: "Med_cond" },
      { character: "n", style: "Med_cond" },
      { character: "d", style: "Med_cond" },
      { character: " ", style: "Med_cond" },
      { character: "t", style: "Med_cond" },
      { character: "a", style: "Med_cond" },
      { character: "l", style: "Med_cond" },
      { character: "k", style: "Med_cond" },
      { character: ")", style: "Med_cond" },
      { character: ".", style: "Med_cond" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "7", style: "" },
      { character: "EN_DASH", style: "" },
      { character: "2", style: "" },
      { character: "8", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "p", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Bring students together and ask several pairs to share the text evidence they found. Students should be able to explain that Nancy shows kindness by trying to help \nOliver and telling Rose the truth about him. Her actions will result in Oliver returning to Mr. Brownlow’s home rather than being handed over to the police. This shows how kindness can have an important and positive effect on someone’s life.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "B", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "N", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: " ", style: "" },
      { character: "FORCED_LINE_BREAK", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "NONBREAKING_SPACE", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "H", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "n", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_B-hd",
    content: "Find Text Evidence Independently\r",
    parentPageName: "6",
    characterStyles: [
      { character: "F", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "T", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "E", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "I", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Ask students to reread pages 29–30 independently to identify more evidence that supports the theme. Students should conclude that Mr. Brownlow shows kindness to Oliver by demanding that Monks share the family inheritance and by giving Oliver a new life and a new home.\r",
    parentPageName: "6",
    characterStyles: [
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "2", style: "" },
      { character: "9", style: "" },
      { character: "EN_DASH", style: "" },
      { character: "3", style: "" },
      { character: "0", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "r", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "B", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "n", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "k", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "g", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "O", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Body-txt",
    content: "Discuss how this close reading has helped students understand that the text evidence supports the theme that showing kindness can have a positive effect on someone’s life.",
    parentPageName: "6",
    characterStyles: [
      { character: "D", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: "c", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "i", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "l", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "u", style: "" },
      { character: "p", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "k", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "SINGLE_RIGHT_QUOTE", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "i", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" }
    ]
  },
  {
    styleName: "Lesson_Table-body-txt",
    content: "What is a central theme of this play and how is it conveyed through particular details?",
    parentPageName: "6",
    characterStyles: [
      { character: "W", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "m", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "f", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "w", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "n", style: "Character Style 1" },
      { character: "v", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "y", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "o", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "g", style: "Character Style 1" },
      { character: "h", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "p", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "c", style: "Character Style 1" },
      { character: "u", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "r", style: "Character Style 1" },
      { character: " ", style: "Character Style 1" },
      { character: "d", style: "Character Style 1" },
      { character: "e", style: "Character Style 1" },
      { character: "t", style: "Character Style 1" },
      { character: "a", style: "Character Style 1" },
      { character: "i", style: "Character Style 1" },
      { character: "l", style: "Character Style 1" },
      { character: "s", style: "Character Style 1" },
      { character: "?", style: "Character Style 1" }
    ]
  }
];
 module.exports = paragraphData;
