const paragraphData = [
  {
    styleName: "A-hd",
    content: "Build Language and Vocabulary\r",
    parentPageName: "11",
    characterStyles: [
      { character: "B", style: "" },
      { character: "u", style: "" },
      { character: "i", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "L", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "V", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Extend Language Concepts: Passive Voice L.6.1\r",
    parentPageName: "11",
    characterStyles: [
      { character: "E", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "L", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "A-subhd" },
      { character: "P", style: "A-subhd" },
      { character: "a", style: "A-subhd" },
      { character: "s", style: "A-subhd" },
      { character: "s", style: "A-subhd" },
      { character: "i", style: "A-subhd" },
      { character: "v", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: " ", style: "A-subhd" },
      { character: "V", style: "A-subhd" },
      { character: "o", style: "A-subhd" },
      { character: "i", style: "A-subhd" },
      { character: "c", style: "A-subhd" },
      { character: "e", style: "A-subhd" },
      { character: " ", style: "" },
      { character: "L", style: "B-hd-CCSS" },
      { character: ".", style: "B-hd-CCSS" },
      { character: "6", style: "B-hd-CCSS" },
      { character: ".", style: "B-hd-CCSS" },
      { character: "1", style: "B-hd-CCSS" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Read the following sentence from page 5: \r",
    parentPageName: "11",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "5", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "11",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: The author uses passive voice throughout the book. Writers use passive voice \nto draw attention to the thing being acted upon, or the object. The subject or the “doer” is less important and sometimes not even identified. In this sentence, the passive voice draws our attention to the natural habitats that are being destroyed.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "W", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "FORCED_LINE_BREAK", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "j", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "j", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "DOUBLE_LEFT_QUOTE", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Have students work in pairs to look through the book for additional examples of passive voice. Ask students to share their findings. Monitor and provide feedback as necessary. Record the examples of passive voice on a chart to refer to throughout the rest of the unit. \r",
    parentPageName: "11",
    characterStyles: [
      { character: "H", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "o", style: "" },
      { character: "o", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "M", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: "b", style: "" },
      { character: "a", style: "" },
      { character: "c", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "g", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Turn and talk. Challenge partners to compose sentences using passive voice based on information in the text. Have partners share their sentences with the rest of the class and explain how the passive voice affects their sentences.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "T", style: "b" },
      { character: "u", style: "b" },
      { character: "r", style: "b" },
      { character: "n", style: "b" },
      { character: " ", style: "b" },
      { character: "a", style: "b" },
      { character: "n", style: "b" },
      { character: "d", style: "b" },
      { character: " ", style: "b" },
      { character: "t", style: "b" },
      { character: "a", style: "b" },
      { character: "l", style: "b" },
      { character: "k", style: "b" },
      { character: ".", style: "b" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "o", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "u", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "m", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "H", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "n", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "s", style: "" },
      { character: "s", style: "" },
      { character: "i", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "v", style: "" },
      { character: "o", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "f", style: "" },
      { character: "f", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
    ],
  },
  {
    styleName: "B-hd",
    content: "Extend Vocabulary Concepts: Synonyms and Antonyms L.6.4, L.6.5\r",
    parentPageName: "11",
    characterStyles: [
      { character: "E", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "V", style: "" },
      { character: "o", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "u", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "y", style: "" },
      { character: " ", style: "" },
      { character: "C", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: "p", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "B-subhd" },
      { character: "y", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "o", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "y", style: "B-subhd" },
      { character: "m", style: "B-subhd" },
      { character: "s", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "a", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "d", style: "B-subhd" },
      { character: " ", style: "B-subhd" },
      { character: "A", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "t", style: "B-subhd" },
      { character: "o", style: "B-subhd" },
      { character: "n", style: "B-subhd" },
      { character: "y", style: "B-subhd" },
      { character: "m", style: "B-subhd" },
      { character: "s", style: "B-subhd" },
      { character: " ", style: "" },
      { character: "L", style: "B-hd-CCSS" },
      { character: ".", style: "B-hd-CCSS" },
      { character: "6", style: "B-hd-CCSS" },
      { character: ".", style: "B-hd-CCSS" },
      { character: "4", style: "B-hd-CCSS" },
      { character: ",", style: "B-hd-CCSS" },
      { character: " ", style: "B-hd-CCSS" },
      { character: "L", style: "B-hd-CCSS" },
      { character: ".", style: "B-hd-CCSS" },
      { character: "6", style: "B-hd-CCSS" },
      { character: ".", style: "B-hd-CCSS" },
      { character: "5", style: "B-hd-CCSS" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Read the following sentence from page 7: \r",
    parentPageName: "11",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "7", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "11",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: Synonyms and antonyms serve two purposes. The variety of words that mean the same or opposite make the text more interesting to read and they help explain difficult concepts. In this sentence, for example, the words land and terrestrial are synonyms, and so are water and aquatic. The use of synonyms in this example enables the author to introduce the reader to more technical terms for familiar concepts.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "S", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "k", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "I", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk bold italic" },
      { character: "l", style: "teacher-talk bold italic" },
      { character: "a", style: "teacher-talk bold italic" },
      { character: "n", style: "teacher-talk bold italic" },
      { character: "d", style: "teacher-talk bold italic" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: "r", style: "teacher-talk bold italic" },
      { character: "r", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: "s", style: "teacher-talk bold italic" },
      { character: "t", style: "teacher-talk bold italic" },
      { character: "r", style: "teacher-talk bold italic" },
      { character: "i", style: "teacher-talk bold italic" },
      { character: "a", style: "teacher-talk bold italic" },
      { character: "l", style: "teacher-talk bold italic" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ",", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk bold italic" },
      { character: "a", style: "teacher-talk bold italic" },
      { character: "t", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: "r", style: "teacher-talk bold italic" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk bold italic" },
      { character: "q", style: "teacher-talk bold italic" },
      { character: "u", style: "teacher-talk bold italic" },
      { character: "a", style: "teacher-talk bold italic" },
      { character: "t", style: "teacher-talk bold italic" },
      { character: "i", style: "teacher-talk bold italic" },
      { character: "c", style: "teacher-talk bold italic" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "x", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "b", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "c", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "Read the following sentence from page 8:\r",
    parentPageName: "11",
    characterStyles: [
      { character: "R", style: "" },
      { character: "e", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "o", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "o", style: "" },
      { character: "w", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "c", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "g", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "8", style: "" },
      { character: ":", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "11",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content:
      "Say: The words extreme and temperate are antonyms. They help readers visualize the range in types of environments.\r",
    parentPageName: "11",
    characterStyles: [
      { character: "S", style: "teacher-talk bold" },
      { character: "a", style: "teacher-talk bold" },
      { character: "y", style: "teacher-talk bold" },
      { character: ":", style: "teacher-talk bold" },
      { character: " ", style: "" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "w", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: "x", style: "teacher-talk bold italic" },
      { character: "t", style: "teacher-talk bold italic" },
      { character: "r", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: "m", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: "m", style: "teacher-talk bold italic" },
      { character: "p", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: "r", style: "teacher-talk bold italic" },
      { character: "a", style: "teacher-talk bold italic" },
      { character: "t", style: "teacher-talk bold italic" },
      { character: "e", style: "teacher-talk bold italic" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "T", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "d", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: "u", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "l", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "z", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "h", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "a", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "g", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "y", style: "teacher-talk" },
      { character: "p", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "f", style: "teacher-talk" },
      { character: " ", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "v", style: "teacher-talk" },
      { character: "i", style: "teacher-talk" },
      { character: "r", style: "teacher-talk" },
      { character: "o", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "m", style: "teacher-talk" },
      { character: "e", style: "teacher-talk" },
      { character: "n", style: "teacher-talk" },
      { character: "t", style: "teacher-talk" },
      { character: "s", style: "teacher-talk" },
      { character: ".", style: "teacher-talk" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "Have students work in pairs to find more examples of synonyms and antonyms in the text. As students share their findings, record them on chart paper titled “Examples of Synonyms and Antonyms.” \r",
    parentPageName: "11",
    characterStyles: [
      { character: "H", style: "" },
      { character: "a", style: "" },
      { character: "v", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "k", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "y", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "y", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "y", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: ".", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "s", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: "s", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "c", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: " ", style: "" },
      { character: "p", style: "" },
      { character: "a", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "E", style: "" },
      { character: "x", style: "" },
      { character: "a", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "f", style: "" },
      { character: " ", style: "" },
      { character: "S", style: "" },
      { character: "y", style: "" },
      { character: "n", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "y", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "A", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "y", style: "" },
      { character: "m", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content: "\r",
    parentPageName: "11",
    characterStyles: [{ character: "", style: "" }],
  },
  {
    styleName: "Body-txt",
    content: "“Around the world, natural habitats are being destroyed.” ",
    parentPageName: "11",
    characterStyles: [
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "A", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "u", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "l", style: "" },
      { character: "d", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "n", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "u", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "e", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "g", style: "" },
      { character: " ", style: "" },
      { character: "d", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "y", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "“Earth habitats fall into two broad categories: land and water, also called ﻿terrestrial﻿ or ﻿aquatic﻿ habitats.” ",
    parentPageName: "11",
    characterStyles: [
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "E", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "f", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: " ", style: "" },
      { character: "i", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "w", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "b", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "a", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "g", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: ":", style: "" },
      { character: " ", style: "" },
      { character: "l", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "w", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: ",", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "s", style: "" },
      { character: "o", style: "" },
      { character: " ", style: "" },
      { character: "c", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "l", style: "" },
      { character: "e", style: "" },
      { character: "d", style: "" },
      { character: " ", style: "" },
      { character: "﻿", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "s", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "i", style: "" },
      { character: "a", style: "" },
      { character: "l", style: "" },
      { character: "﻿", style: "" },
      { character: " ", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: " ", style: "" },
      { character: "﻿", style: "" },
      { character: "a", style: "" },
      { character: "q", style: "" },
      { character: "u", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "i", style: "" },
      { character: "c", style: "" },
      { character: "﻿", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
      { character: " ", style: "" },
    ],
  },
  {
    styleName: "Body-txt",
    content:
      "“Some habitats are more extreme than the temperate environments.”",
    parentPageName: "11",
    characterStyles: [
      { character: "DOUBLE_LEFT_QUOTE", style: "" },
      { character: "S", style: "" },
      { character: "o", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "b", style: "" },
      { character: "i", style: "" },
      { character: "t", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: " ", style: "" },
      { character: "a", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "m", style: "" },
      { character: "o", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "x", style: "" },
      { character: "t", style: "" },
      { character: "r", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "a", style: "" },
      { character: "n", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "h", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: "m", style: "" },
      { character: "p", style: "" },
      { character: "e", style: "" },
      { character: "r", style: "" },
      { character: "a", style: "" },
      { character: "t", style: "" },
      { character: "e", style: "" },
      { character: " ", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "v", style: "" },
      { character: "i", style: "" },
      { character: "r", style: "" },
      { character: "o", style: "" },
      { character: "n", style: "" },
      { character: "m", style: "" },
      { character: "e", style: "" },
      { character: "n", style: "" },
      { character: "t", style: "" },
      { character: "s", style: "" },
      { character: ".", style: "" },
      { character: "DOUBLE_RIGHT_QUOTE", style: "" },
    ],
  },
];
module.exports = paragraphData;
